### ISSUE TITLE
strmxor doesn't have klayout's XOR Tool "Summarize missing layout's" feature

### ISSUE THREAD

**Issue by stefanottili** [KLayout/klayout#1024]
It would be nice to have this option for strmxor, that way it'll have the same features as klayout's XOR Tool.
And it would be possible to compare strmxor results with other xor solutions too.

**Comment by klayoutmatthias** [comment]
#1024 is for binary lovers :)

**Comment by stefanottili** [comment]
scratch that, -l  or --layer-details works as advertised, sorry for the noise.
