### ISSUE TITLE
strm2oas --lefdef-map reads DIEAREA and placement BLOCKAGE even when commented out or being undefined

### ISSUE THREAD

**Issue by stefanottili** [KLayout/klayout#1050]
When using --lefdef-map without DIEAREA or BLOCKAGE one should get a warning about an undefined mapping.
Currently these two get assigned layer:datatype 70:0 and 71:0 even when commented out or being undefined.

#DIEAREA ALL 10 0
#BLOCKAGE ALL 11 0

This is probably true for the REGION and GROUPS mapping too.

**Comment by klayoutmatthias** [comment]
Right. That is a leftover from times when there was no DIEAREA, REGION or BLOCKAGE in the mapping file.

I can easily fix this, but this means that with a mapping file, DIEAREA, REGION or BLOCKAGE are mandatory if you want to see these layers.

Matthias
