### ISSUE TITLE
Does method layout.read always return layouts involving shapes of simple_polygon rather than polygon?

### ISSUE THREAD

**Issue by Z-KN** [KLayout/klayout#1063]
Firstly I create a "db.Polygon" with holes and execute layout.write("xxx.gds"), then load it through "layout.read("xxx.gds"). When I analyze the shape in the loaded layout, the returned shape will always be "db.SimplePolygon" with holes resolved. Also, the KLayout viewer will display a simple polygon in "Polygon Properties". It seems the reading method automatically converts a complex polygon to a simple polygon. However, I want the raw complex polygon with holes instead of a simple polygon, which sometimes has edges and points overlapped.

![image](https://user-images.githubusercontent.com/50490656/163705489-f0e1afc2-4f73-4a9d-b1f0-c7582f27387e.png)

What should I do?

**Comment by ejprinz** [comment]
I think GDSII cannot store polygons with holes. Try saving in OASIS format and see whether this works.

**Comment by Z-KN** [comment]
Thank you, I agree. The user should pre-process the layout or turn to another format.
