### ISSUE TITLE
Console does not show in macro editor

### ISSUE THREAD

**Issue by jamesmeiklejohn** [KLayout/klayout#1064]
On Windows 11 with a new install of KLayout 0.27.8, the console does not show below the editor window.

![image](https://user-images.githubusercontent.com/30795767/163994211-223e92dd-29f7-4cec-a43c-1f85379727d1.png)

**Comment by Kazzz-S** [comment]
I'm not a Windows 11 user, but...

![Console-Win11](https://user-images.githubusercontent.com/16847255/164006894-870cfacb-6069-4a62-a0da-25e632b39a5d.png)

**Comment by jamesmeiklejohn** [comment]
I tried that as well as adjusting the size of the window and it doesn't show - also tried with a different monitor resolution.

**Comment by klayoutmatthias** [comment]
You can try to clear the configuration cache. Maybe there is something kept there which blocks the readjustment.

To clear the configuration, remove or rename the file called "klayoutrc" inside KLayout's home folder. On Windows you will usually find this file in c:\users\youraccountname\KLayout. This should restore the original settings and clear any stored display configurations.

Matthias

**Comment by jamesmeiklejohn** [comment]
thanks this worked! Possibly upgrading to Windows 11 is the origin of this if the cache was generated on 10?

**Comment by klayoutmatthias** [comment]
Possibly. This specific configuration cache is managed by Qt and it is hard to debug this issue. 

Matthias

**Comment by NemoAndrea** [comment]
> I'm not a Windows 11 user, but...
> 
> ![Console-Win11](https://user-images.githubusercontent.com/16847255/164006894-870cfacb-6069-4a62-a0da-25e632b39a5d.png)

For me removing the `klayoutrc` file did not solve the issue (Windows 10), but from the image above I realised I could drag the console into view from the right side of the text editor window. So instead of below the text editor (as in quoted image), from the right side. 

Adding in case other people have the same issue.
