### ISSUE TITLE
Why this project named KLayout

### ISSUE THREAD

**Issue by YifeiCN** [KLayout/klayout#1066]
I'm curious about the meaning of K :)

**Comment by mi-and-core** [comment]
One of many interpretations: K stands for the first letter of Matthias' last name

**Comment by klayoutmatthias** [comment]
Let me tell you it's not for "KDE" :)

The short story is that I published this project under the name "Microscope" initially, but then I learned that this is a registered trademark for a CAD file viewer. So I had to change it quickly and "KLayout" simply was the first thing that came to my mind. 

You can take a look at the archived old documentation here: https://www.klayout.de/0.16/rba_index.html - the background image of the left panel still shows a microscope:

![image](https://user-images.githubusercontent.com/25720841/164787017-dc7ffd3e-b7fa-4543-8fea-433f5e88ad88.png)
 
Matthias

**Comment by YifeiCN** [comment]
> 

I didn't expect to get your reply in person. Thank you very much for your reply. At first, I thought KLayout meant the king of layout ; )
