### ISSUE TITLE
Mac: Fill Tool missing most parameters

### ISSUE THREAD

**Issue by demisjohn** [KLayout/klayout#1094]
It's my first time using the Edit>Utilities>`Fill Tool` in KLayout, so it's entirely possible I'm just mistaken here.

According to [this video](https://www.youtube.com/watch?v=uP8QQ_Ggnkg), the `Fill Tool` should pop up with options for "Fill Cell" (which cell to perform filling with) like this:
<img width="656" alt="Video showing fill tool dialogue" src="https://user-images.githubusercontent.com/5370181/172776704-0acf9bcc-2a5f-4017-b61c-4d1d88910279.png">

However, on the Mac version of Klayout (originally tried 0.27.4, then upgraded to 0.27.10 - no difference), I am missing most of the required parameters:
<img width="751" alt="Mac OS screenshot of fill tool dialogue" src="https://user-images.githubusercontent.com/5370181/172776916-53103bc6-1925-4d1e-9902-1b1ea52e76bc.png">

If I hit [OK] I get "Fill cell not found:" indicating an empty parameter sent to the function.
<img width="242" alt="Error: Fill cell not found" src="https://user-images.githubusercontent.com/5370181/172777162-de5c7351-6382-4ee9-98a5-07dab9fbf2dc.png">

Perhaps there's a bug in the MacOS version causing these fields to be missing?

### Versions
MacOS 12.2.1 (21D62)
KLayout 0.27.10
<img width="900" alt="KLayout Version" src="https://user-images.githubusercontent.com/5370181/172777361-284e3fd1-37a6-4a03-83a3-8eebbc4ce605.png">

**Comment by Kazzz-S** [comment]
I have not used `Edit>Utilities>Fill Tool`. So I cannot instruct how to use it.

However, I think there was a change in the dialog GUI design from 0.26.x to 0.27.x.
The video tutorial uses 0.26.4.

My macOS version is 12.4 (Monterey).
Therefore, I cannot run the KLayout bundled with Python 2.7.18 you are using.
So, I've tested with the nearest one.

Please compare the images below.
In my observation, all parameter fields (and more) are distributed in four tabs in the latest version.

## 0.26.4 ##
![0264A](https://user-images.githubusercontent.com/16847255/172820305-0159d743-b35d-448c-bd0e-6252a836f7f0.png)
![0264B](https://user-images.githubusercontent.com/16847255/172820345-9955d711-a33d-47d5-881f-884f358ae2c8.png)

## 0.27.10 ##
![02710A](https://user-images.githubusercontent.com/16847255/172820535-84a11ce1-d075-4a87-b047-c62dc3c9d480.png)
![02710B](https://user-images.githubusercontent.com/16847255/172820552-5a5e7e94-dc8c-4c4e-a8c4-5ef5243ab545.png)
![02710C](https://user-images.githubusercontent.com/16847255/172820557-03d08155-a601-4e66-88ab-31cac4d9819d.png)
![02710D](https://user-images.githubusercontent.com/16847255/172820562-5e794e82-8cf1-4d1b-b303-55ad2b97b0b0.png)
![02710E](https://user-images.githubusercontent.com/16847255/172820564-8a6bbde4-c1c9-4721-9187-464a59bf7b83.png)

**Comment by demisjohn** [comment]
Ah I see - I have to fill out fields in ALL FOUR tabs - yes indeed this works. It seemed like each tab was a different function, rather than being parameters of the same function. 

This works as expected then!
