### ISSUE TITLE
Change oasis writer defaults to strict + cblocks, discourage the usage of oas.gz 

### ISSUE THREAD

**Issue by stefanottili** [KLayout/klayout#1097]
In order to allow multithreaded oasis reading, would be good for 0.28 to change the default options to write strict oasis with cblocks and to discourage using .gz files.

**Comment by klayoutmatthias** [comment]
Changing defaults is easy, but discouraging .gz is difficult - whenever you add ".gz" it's zipped. I don't want to skip that option entirely.

**Comment by stefanottili** [comment]
Discouraging as in pop up a warning or info message explaining that cblocks are already compressing the data.

On Jun 15, 2022, at 22:45, Matthias Köfferlein ***@***.***> wrote:

﻿
Changing defaults is easy, but discouraging .gz is difficult - whenever you add ".gz" it's zipped. I don't want to skip that option entirely.
