### ISSUE TITLE
External DLL file errors after MSYS2 compilation

### ISSUE THREAD

**Issue by nikosavola** [KLayout/klayout#1108]
Hello Matthias,

I'm confused on how one should get the external DLLs when building.
I'm getting the following errors for some Python, Ruby and Qt DLLs after compiling with MSYS2 on Windows.

![image](https://user-images.githubusercontent.com/7860886/176433396-238a5bb9-3014-433a-9d24-277a6180dffa.png)

Should the building automatically copy these and something failed, or did I miss some part of the process. I ran `build.sh` in MSYS2 MinGW x64.

**Comment by klayoutmatthias** [comment]
I think you are trying to run the .exe outside the MSYS shell I suppose. In this case you either need to set the PATH to include the place of the libpython.3.9.dll or copy .exe and all required DLLs into one place. That is how building on Windows is like. 

The easiest is to run KLayout from the MSYS2 prompt.

Matthias

**Comment by nikosavola** [comment]
> I think you are trying to run the .exe outside the MSYS shell I suppose. In this case you either need to set the PATH to include the place of the libpython.3.9.dll or copy .exe and all required DLLs into one place. That is how building on Windows is like.
> 
> The easiest is to run KLayout from the MSYS2 prompt.
> 
> Matthias

Ah, thank you. I didn't know it had to be run from there.
