### ISSUE TITLE
Palettes don't respect Windows scaling

### ISSUE THREAD

**Issue by nikosavola** [KLayout/klayout#1113]
Currently color palettes and stipples in the _Layers_ tabs don't respect Windows scaling. The text for the layer names does, leaving the examples a bit smaller.

Additionally, the Palettes (Color, Stipple, Line Style) in the settings don't follow Windows scaling either, resulting in the following between two monitors with different scaling

![image](https://user-images.githubusercontent.com/7860886/177262739-e505ed62-57df-4501-8c3a-445c805db931.png)

![image](https://user-images.githubusercontent.com/7860886/177262721-895b0e44-d7b4-4501-b5f8-631d505a35b1.png)

Maybe similar to #94 

A solution might exist by setting a reference DPI and scaling that https://stackoverflow.com/a/60318784

**Comment by klayoutmatthias** [comment]
I don't own high-DPI hardware, so it's difficult for me to reproduce the issue. But I'll try.

**Comment by klayoutmatthias** [comment]
0.28 will fix this issue.
