### ISSUE TITLE
KLayout for macOS Monterey (M1)

### ISSUE THREAD

**Issue by pavan-PVk** [KLayout/klayout#1115]
Hie, I am trying to install KLayout for my lithography patterning work in Mac. It's not working in my computer. 

I tried to install "[ST-klayout-0.27.10-macOS-Catalina-1-qt5MP-RsysPsys.dmg](https://www.klayout.org/downloads/MacOS/ST-klayout-0.27.10-macOS-Catalina-1-qt5MP-RsysPsys.dmg)" version and the message is "klayout” cannot be opened because the developer cannot be verified" 

This is the detailed report:

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               klayout [1756]
Path:                  /Applications/klayout.app/Contents/MacOS/klayout
Identifier:            de.klayout
Version:               0.27.5 (0.27.5)
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-07-07 11:38:41.0976 -0500
OS Version:            macOS 12.4 (21F79)
Report Version:        12
Anonymous UUID:        C2A832A4-ED3F-0435-E70B-C0BC75520B86

Sleep/Wake UUID:       C964A25F-D4CE-41C6-8E05-3DEBBC59969D

Time Awake Since Boot: 5900 seconds
Time Since Wake:       997 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /System/Library/Frameworks/Python.framework/Versions/2.7/Python
Referenced from: /Applications/klayout.app/Contents/MacOS/klayout
Reason: tried: '/System/Library/Frameworks/Python.framework/Versions/2.7/Python' (no such file), '/Library/Frameworks/Python.framework/Versions/2.7/Python' (no such file)
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   Rosetta Runtime Routines	       0x102a16940 ???
1   <translation info unavailable>	       0x102a601a4 ???
2   dyld                          	       0x202d6c1d2 abort_with_payload_wrapper_internal + 80
3   dyld                          	       0x202d6c204 abort_with_payload + 9
4   dyld                          	       0x202d1a76f dyld4::halt(char const*) + 375
5   dyld                          	       0x202d165a5 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3995
6   dyld                          	       0x202d154d4 start + 388

Thread 1:: com.apple.rosetta.exceptionserver
0   runtime                       	    0x7ff7ffee29c4 0x7ff7ffede000 + 18884
1   runtime                       	    0x7ff7ffef0460 0x7ff7ffede000 + 74848
2   runtime                       	    0x7ff7ffef1ed8 0x7ff7ffede000 + 81624

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x00000003097b2ae0   x3: 0x0000000000000085
    x4: 0x00000003097b26e0   x5: 0x0000000000000000   x6: 0xbdd8d2dfa7570060   x7: 0x00000020097b26f0
    x8: 0x00000003097b26e0   x9: 0x0000000000000000  x10: 0x0000000000000085  x11: 0x00000003097b26e0
   x12: 0x0000000000000085  x13: 0x00000003097b2ae0  x14: 0x0000000000000001  x15: 0x0000000000000006
   x16: 0x0000000000000209  x17: 0x0000000000000000  x18: 0x800000010aa7fb70  x19: 0x0000000102a0c000
   x20: 0x00000000000007ff  x21: 0x000000010aa84fa0  x22: 0xffffffffffffffff  x23: 0x0000000102a16914
   x24: 0x0000000202d6c1d2  x25: 0x0000000102a161f4  x26: 0x0000000102a5e840  x27: 0x0000000000000000
   x28: 0x0000000202d560be   fp: 0x000000002c000000   lr: 0x0000000102a601a4
    sp: 0x000000010aa7fb70   pc: 0x0000000102a16940 cpsr: 0x80001000
   far: 0x0000000102a60000  esr: 0x56000080  Address size fault

Binary Images:
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x202d10000 -        0x202d7bfff dyld (*) <b70ce1ec-b902-3852-8268-05de00bfa8d5> /usr/lib/dyld
    0x7ff7ffede000 -     0x7ff7fff0dfff runtime (*) <0ee8ce32-639c-316a-9551-dab9a2e0c8a5> /usr/libexec/rosetta/runtime

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1272K resident=0K(0%) swapped_out_or_unallocated=1272K(100%)
Writable regions: Total=155.2M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=155.2M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Rosetta Arena                     4096K        2 
Rosetta Generic                    764K      188 
Rosetta IndirectBranch              32K        1 
Rosetta JIT                      128.0M        1 
Rosetta Return Stack                20K        2 
Rosetta Thread Context              20K        2 
Stack                             8176K        1 
Stack Guard                       56.0M        1 
VM_ALLOCATE                       13.3M        5 
VM_ALLOCATE (reserved)               4K        1         reserved VM address space (unallocated)
__DATA                             128K        6 
__DATA_CONST                        80K        1 
__LINKEDIT                         280K        7 
__TEXT                            1024K        4 
dyld private memory               1024K        1 
mapped file                        6.1G       28 
===========                     =======  ======= 
TOTAL                              6.3G      251 
TOTAL, minus reserved VM space     6.3G      251 

-----------
Full Report
-----------

{"app_name":"klayout","timestamp":"2022-07-07 11:38:41.00 -0500","app_version":"0.27.5","slice_uuid":"a4bda4bb-beb8-3926-beb9-b48ee9814d1e","build_version":"0.27.5","platform":1,"bundleID":"de.klayout","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.4 (21F79)","incident_id":"DE496086-AE47-4DE7-B32B-56BF1F5408A3","name":"klayout"}
{
  "uptime" : 5900,
  "procLaunch" : "2022-07-07 11:38:33.8456 -0500",
  "procRole" : "Background",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookAir10,1",
  "procStartAbsTime" : 141591629298,
  "coalitionID" : 1711,
  "osVersion" : {
    "train" : "macOS 12.4",
    "build" : "21F79",
    "releaseType" : "User"
  },
  "captureTime" : "2022-07-07 11:38:41.0976 -0500",
  "incident" : "DE496086-AE47-4DE7-B32B-56BF1F5408A3",
  "bug_type" : "309",
  "pid" : 1756,
  "procExitAbsTime" : 141765681096,
  "translated" : true,
  "cpuType" : "X86-64",
  "procName" : "klayout",
  "procPath" : "\/Applications\/klayout.app\/Contents\/MacOS\/klayout",
  "bundleInfo" : {"CFBundleShortVersionString":"0.27.5","CFBundleVersion":"0.27.5","CFBundleIdentifier":"de.klayout"},
  "storeInfo" : {"deviceIdentifierForVendor":"D189A253-3F76-537D-ABBD-E561B0284835","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "de.klayout",
  "crashReporterKey" : "C2A832A4-ED3F-0435-E70B-C0BC75520B86",
  "wakeTime" : 997,
  "sleepWakeUUID" : "C964A25F-D4CE-41C6-8E05-3DEBBC59969D",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: \/System\/Library\/Frameworks\/Python.framework\/Versions\/2.7\/Python","Referenced from: \/Applications\/klayout.app\/Contents\/MacOS\/klayout","Reason: tried: '\/System\/Library\/Frameworks\/Python.framework\/Versions\/2.7\/Python' (no such file), '\/Library\/Frameworks\/Python.framework\/Versions\/2.7\/Python' (no such file)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":87745,"threadState":{"x":[{"value":6},{"value":1},{"value":13043968736},{"value":133},{"value":13043967712},{"value":0},{"value":13679915726164918368},{"value":137598019312},{"value":13043967712},{"value":0},{"value":133},{"value":13043967712},{"value":133},{"value":13043968736},{"value":1},{"value":6},{"value":521},{"value":0},{"value":9223372041328524144},{"value":4339056640},{"value":2047},{"value":4473769888},{"value":18446744073709551615},{"value":4339099924},{"value":8637563346,"symbolLocation":80,"symbol":"abort_with_payload_wrapper_internal"},{"value":4339098100},{"value":4339394624},{"value":0},{"value":8637472958,"symbolLocation":10,"symbol":"__abort_with_payload"}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4339401124},"cpsr":{"value":2147487744},"fp":{"value":738197504},"sp":{"value":4473748336},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":4339099968,"matchesCrashFrame":1},"far":{"value":4339400704}},"frames":[{"imageOffset":4339099968,"region":"Rosetta Runtime Routines","symbolLocation":10560,"imageIndex":0},{"imageOffset":4339401124,"region":"<translation info unavailable>","imageIndex":0},{"imageOffset":377298,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":80,"imageIndex":1},{"imageOffset":377348,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":1},{"imageOffset":42863,"symbol":"dyld4::halt(char const*)","symbolLocation":375,"imageIndex":1},{"imageOffset":26021,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3995,"imageIndex":1},{"imageOffset":21716,"symbol":"start","symbolLocation":388,"imageIndex":1}]},{"id":87856,"name":"com.apple.rosetta.exceptionserver","frames":[{"imageOffset":18884,"imageIndex":2},{"imageOffset":74848,"imageIndex":2},{"imageOffset":81624,"imageIndex":2}]}],
  "usedImages" : [
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 8637186048,
    "size" : 442368,
    "uuid" : "b70ce1ec-b902-3852-8268-05de00bfa8d5",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 140703127429120,
    "size" : 196608,
    "uuid" : "0ee8ce32-639c-316a-9551-dab9a2e0c8a5",
    "path" : "\/usr\/libexec\/rosetta\/runtime",
    "name" : "runtime"
  }
],
  "sharedCache" : {
  "base" : 140703530680320,
  "size" : 15220686848,
  "uuid" : "53b6853f-0bc3-33f5-be72-1aca3a188ff8"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1272K resident=0K(0%) swapped_out_or_unallocated=1272K(100%)\nWritable regions: Total=155.2M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=155.2M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nRosetta Arena                     4096K        2 \nRosetta Generic                    764K      188 \nRosetta IndirectBranch              32K        1 \nRosetta JIT                      128.0M        1 \nRosetta Return Stack                20K        2 \nRosetta Thread Context              20K        2 \nStack                             8176K        1 \nStack Guard                       56.0M        1 \nVM_ALLOCATE                       13.3M        5 \nVM_ALLOCATE (reserved)               4K        1         reserved VM address space (unallocated)\n__DATA                             128K        6 \n__DATA_CONST                        80K        1 \n__LINKEDIT                         280K        7 \n__TEXT                            1024K        4 \ndyld private memory               1024K        1 \nmapped file                        6.1G       28 \n===========                     =======  ======= \nTOTAL                              6.3G      251 \nTOTAL, minus reserved VM space     6.3G      251 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "61af99aeda72d16a4beb7756",
      "factorPackIds" : {
        "SIRI_DIALOG_ASSETS" : "62b9afba7e9ada388efffaa0"
      },
      "deploymentId" : 240000237
    },
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {

      },
      "deploymentId" : 240000393
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookAir10,1, BootROM 7459.121.3, proc 8:4:4 processors, 16 GB, SMC 
Graphics: Apple M1, Apple M1, Built-In
Display: Color LCD, 2560 x 1600 Retina, Main, MirrorOff, Online
Memory Module: LPDDR4
AirPort: Wi-Fi, wl0: Mar 23 2022 19:57:59 version 18.60.27.0.7.8.129 FWID 01-570be953
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Air, Apple Inc.
Thunderbolt Bus: MacBook Air, Apple Inc.

Can someone help me out??

**Comment by Kazzz-S** [comment]
Hi, 

The primary reason is Monterey no longer provides Python 2.7.
```
:
Library not loaded: /System/Library/Frameworks/Python.framework/Versions/2.7/Python`
:
```
Please refer to #1091. I quote the relevant part below.

----
## For the latest macOS Monterey (12.4) ##
Four macOS DMGs for **Monterey** are available for experimental purposes.

**LW- and HW- packages use Python 3.8 in MacPorts, Homebrew and Anaconda3.**
|Srl.No.|Target OS|DMG file name|Qt5|Ruby|Python|Remarks|
|:------:|:--------:|:--------------:|:---:|:----:|:-----:|:--------:|
31a|~~Monterey (12.4)~~|~~ST-klayout-0.27.10-macOS-Monterey-1-qt5MP-RsysPsys.dmg~~|~~MacPorts~~|~~OS-bundled~~|~~OS-bundled~~|(31a)|
31b|~~Catalina (10.15)~~|~~ST-klayout-0.27.10-macOS-Catalina-1-qt5MP-RsysPsys.dmg~~|~~MacPorts~~|~~OS-bundled~~|~~OS-bundled~~|(31b)|
32|Monterey (12.4) with MacPorts dev. env.|LW-klayout-0.27.10-macOS-Monterey-1-qt5MP-Rmp27Pmp38.dmg|MacPorts|MacPorts|MacPorts|(22)|
33|Monterey (12.4) with Homebrew dev. env.|LW-klayout-0.27.10-macOS-Monterey-1-qt5Brew-Rhb27Phb38.dmg|Homebrew|Homebrew|Homebrew|(33)|
34|Monterey (12.4) with Anaconda3 dev. env.|LW-klayout-0.27.10-macOS-Monterey-1-qt5Ana3-Rana3Pana3.dmg|Anaconda3|Anaconda3|Anaconda3|(34)|
35|Monterey (12.4)|HW-klayout-0.27.10-macOS-Monterey-1-qt5Brew-RsysPhb38.dmg|Homebrew|OS-bundled|Homebrew|(35)|

(31a) **NOT PROVIDED**; The ST-* package is no longer provided since Xcode >= 13.1 does not link the legacy Python 2.7 library.
(31b) **Monterey 12.3.1 finally eliminated Python-2.7 binary. Hence, ST-\* package no longer runs.**
(32) **experimental**; shares MacPorts development environment; for those who have the matching dev. env.
(33) **experimental**; shares Homebrew development environment; for those who have the matching dev. env.
(34) **experimental**; shares Anaconda3 development environment; for those who have the matching dev. env.
(35) **experimental**; shares OS-bundled Ruby2.6; Qt5 and Python-3.8 from Homebrew are embedded, hence, heavy.

----
You have four options to try: Srl. No. 32, 33, 34, and 35.
* Srl. No. 35 will be the easiest for the first trial.
* If you are an active Pythonist, I recommend one of the other three. However, you need to install a matching development environment + XCode.

Please note that I have not tried any of these on an M1 Mac since I don't own it. However, I heard they work.

Regards,
Kazzz-S

**Comment by pavan-PVk** [comment]
Thank you @Kazzz-S  that worked for me.
