### ISSUE TITLE
KLayout editor mode setup in Mac M1

### ISSUE THREAD

**Issue by pavan-PVk** [KLayout/klayout#1118]
Hello, I am pretty new to this software. I am trying to open klayout in editor mode in MacBook Air. I couldn't possibly find the easiest way to do it as in windows. Also tell me how to set the editor mode as default instead of the viewer mode that appears for me now. Can anyone help me with that?

**Comment by Kazzz-S** [comment]
Hi,

![EditorMode](https://user-images.githubusercontent.com/16847255/178598962-a7beadb4-824b-4d54-995d-d2f07fed3955.png)

The setup parameters, including this one, are stored in `$HOME/.klayout/klayoutrc` by default.

Kazzz-S

**Comment by pavan-PVk** [comment]
Thank you @Kazzz-S.
