### ISSUE TITLE
GPU acceleration

### ISSUE THREAD

**Issue by Blebowski** [KLayout/klayout#1123]
Hello,

we are attempting to use klayout (0.27.8 - Packaged version) to view GDSII of a chip we just taped-out.
We run on virtual PC with 4 core / 8 GB RAM. The chip is size about 1M std gates, multiple memory macros,
final GDS. When I open full chip layout (all layers enabled), the drawing of all layers takes about 10-15 seconds.
Most of the time when I zoom, this procedure will repeat (though when zooming in on a smaller portion, re-draw takes less).

Our PC is virtual with no GPU. My question is: Does Klayout have better performance when we had GPU available
(e.g. does it make use of QTs OpenGL acceleration)? It is no problem to get a GPU (either within the virtual machine,
or on new bare-metal server we are preparing), but we will not buy it if it does not bring any performance benefits.

**Comment by klayoutmatthias** [comment]
No, there is no GPU involved.

8GB is quite a little for viewing larger layouts. That is almost taken by Windows itself. Rough memory requirements for GDS are 3x the original GDS size.

For less memory footprint you should make sure you use viewer mode.

Drawing is asynchronous, so you should be able to zoom and pan while drawing happens. A full detailed view of a 1M std cell layout with memory blocks and deeply nested hierarchy is pretty complex, so don't expect snappy response here.

You can speed up by enabling multiple threads for drawing in File/Setup here:

![image](https://user-images.githubusercontent.com/25720841/180620990-8fb0cc16-ec93-4ae9-9f35-0c42991dfec9.png)

BTW: I'd appreciate if you use the forum (https://www.klayout.de/forum/) for questions. This is a bug tracker.

Matthias
