### ISSUE TITLE
Issues with running Klayout in Ubuntu 22.04

### ISSUE THREAD

**Issue by AbhishekDas2000** [KLayout/klayout#1127]
Prebuilt binaries provided in the website is not running properly in Ubuntu 22.04
On running it on terminal, it shows the following error
`Info: Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Aborted (core dumped)`

**Comment by klayoutmatthias** [comment]
Set QT_QPA_PLATFORM=wayland as the message says. That's a Qt issue.
