### ISSUE TITLE
How can I develope KLayout on web page

### ISSUE THREAD

**Issue by ooksang** [KLayout/klayout#1130]
KLayout is great. I am very appreciate your work.
Gdsfactory and KLayout are very useful tool for me.

I want make a 'web based viewer' not based on QT.
But I don't know how do I start with.

When I have searched key word 'web' in issues, discussion,
some answers said about QT-less, canvas to canvas.

Are there some documents for that?
or can anyone give me some guide?

**Comment by klayoutmatthias** [comment]
There is a project ongoing exactly for this. For the discussion see here: https://github.com/KLayout/klayout/issues/1082

Matthias
