### ISSUE TITLE
LEF produce pin on polygons places pin label off the shape

### ISSUE THREAD

**Issue by arlpetergadfort** [KLayout/klayout#1132]
When reading in a LEF file that contains a POLYGON pin (such as an L shape), the label that is produced falls outside the shape itself.
Here is an example of this:
<img width="553" alt="pin_placement" src="https://user-images.githubusercontent.com/46405338/181934866-16ffb29a-da67-495c-8056-9d9270f86edb.png">

It appears to be a bug, I would have anticipated the pin label getting put inside the POLYGON shape.
I've attached the LEF file I used to make the image above: [POLYGON_PIN.zip](https://github.com/KLayout/klayout/files/9226990/POLYGON_PIN.zip)

Please let me know if you need anything else. Thanks.

**Comment by klayoutmatthias** [comment]
Well, so far all pin polygons have been convex and taking the center of the bounding box was sufficient ...

Anyway, generating a point inside a polygon in the generic case isn't trivial. But I can make sure, the label is at a corner of the polygon.

Will this be sufficient?

Matthias

**Comment by arlpetergadfort** [comment]
> Well, so far all pin polygons have been convex and taking the center of the bounding box was sufficient ...
> 
> Anyway, generating a point inside a polygon in the generic case isn't trivial. But I can make sure, the label is at a corner of the polygon.
> 
> Will this be sufficient?
> 
> Matthias

Hi Matthias,

Yes, that should be sufficient, as the pins in the PDK I derived this from puts them on the left edge and bottom edge of the shape, so I think any point on the perimeter will work.

Thanks for getting back to me on this.

**Comment by klayoutmatthias** [comment]
Ok, so I'll put them here unless the pin is actually a rectangle:

![image](https://user-images.githubusercontent.com/25720841/182041013-4801c7ae-d04f-4a7b-9187-f5e7146ddcef.png)

Matthias

**Comment by arlpetergadfort** [comment]
> Ok, so I'll put them here unless the pin is actually a rectangle:
> 
> ![image](https://user-images.githubusercontent.com/25720841/182041013-4801c7ae-d04f-4a7b-9187-f5e7146ddcef.png)
> 
> Matthias

Matthias, that would be perfect.

Thanks.
