### ISSUE TITLE
Illegible overlapping Cell names

### ISSUE THREAD

**Issue by demisjohn** [KLayout/klayout#1163]
When multiple cells have overlapping origins, the title of the Cell is very difficulty to read.  Although text is outlines in white, and clicking on the cell cycles which is in front, this still is rather difficult to read.

This is only 2 names overlapping, more gets even more difficult:
![Screen Shot 2022-09-28 at 7 13 11 PM](https://user-images.githubusercontent.com/5370181/192923531-550cfeb7-2e3a-4c31-bb60-4fffc3d936f6.png)

May I suggest to grey the background texts, and only the frontmost is black - perhaps that would make it easier to read.  Hard to know unless you try it though.

This is a GUI issue that constantly crops up, and is difficult to circumvent. The best I've figure out is to click and watch the status bar which tells me what I'm clicking on - and make a mental list of the objects' names.

**Comment by klayoutmatthias** [comment]
There are options to configure this already.

First you can configure the way, cell boxes are drawn (here: "Cell box colors")

![image](https://user-images.githubusercontent.com/25720841/193098418-937ae457-99f8-4d8e-a83f-680278efbe5c.png)

which gives you:

![image](https://user-images.githubusercontent.com/25720841/193098205-fb807084-c156-4cf5-a147-6d2be3b6fb1d.png)

Then you can configure the selection color to some contrast color (here: "Marker color"):

![image](https://user-images.githubusercontent.com/25720841/193098905-9743dcfc-eb68-4123-8192-79533d4f962b.png)

Which gives you that:

![image](https://user-images.githubusercontent.com/25720841/193099160-ae1825b0-b3f8-44a8-82cb-b80d34c3662d.png)

and

![image](https://user-images.githubusercontent.com/25720841/193099319-2d55a020-4b13-4304-b215-6015d6f7ea32.png)


Matthias

**Comment by demisjohn** [comment]
@klayoutmatthias can we make your above settings the default for the app? That would indeed solve this issue - with the current selection’s text always being legible.

**Comment by demisjohn** [comment]
That’s a great idea - I’ll make & distribute an RC file for our users.
