### ISSUE TITLE
I built klayout on Windows, but the klayout.exe could not be launched

### ISSUE THREAD

**Issue by windywater** [KLayout/klayout#1218]
I built 0.27.12 on Windows with MSVC 2017, all the exe and dlls were built, but when I run klayout.exe, the GUI did not appear.
Did I miss some dependencies or resources?

**Comment by klayoutmatthias** [comment]
How should I know? I don't have access to your system.

Install MSYS bash and run from this comment line - this will give you any messages that may be printed to stdout/stderr. Alternatively try to redirect stdout/stderr to a file on cmd.exe. AFAIK windows itself does provide ways to catching this output.
