### ISSUE TITLE
Add py.typed file to klayout python package

### ISSUE THREAD

**Issue by sebastian-goeldi** [KLayout/klayout#1220]
Hi @klayoutmatthias and @thomaslima ,

Thanks so much for the new type hinted versions :)

One little thing that I am currently missing is the `py.typed` file in the parent folder of the package. mypy for example will not work without this (it will complain "this module is not type hinted"). The file doesn't need to contain anything, just needs to be present. Here's the PEP on it https://peps.python.org/pep-0561/#packaging-type-information

**Comment by thomaslima** [comment]
Hello @sebastian-goeldi Thanks for pointing this out. Would you mind creating a PR for this?

Thanks,
Thomas
