### ISSUE TITLE
Add Python 3.11.1 to PyPi klayout module build

### ISSUE THREAD

**Issue by ejprinz** [KLayout/klayout#1224]
I found that Python 3.11.1 works with the KLayout module but it has been built from source. At some point please add Python 3.11.1 to the PyPi files. This Python version is a bit faster than Python 3.10 and older.

**Comment by klayoutmatthias** [comment]
I bumped pypa/cibuildwheel to v2.11.3 which to my understanding should enable Python 3.11. Let's see if that works.

**Comment by joamatab** [comment]
Hi Matthias,

i think to make it work for python3.11 you need to trigger a new release

![image](https://user-images.githubusercontent.com/4514346/208977898-4659a12b-07b9-4643-b341-fd73889ecb8b.png)

![image](https://user-images.githubusercontent.com/4514346/208978115-f8c5d708-9010-4c16-9af3-05a07a71becf.png)


https://github.com/gdsfactory/gdsfactory/issues/940

**Comment by ejprinz** [comment]
Hi Joaquin:
I was able to install klayout in Python 3.11.1 with pip install but I had
to first install two dependencies which I didn't have installed yet (in
Ubuntu 22.04 LTS):
IIRC the packages were: libxml2-dev, libxslt-dev
So check the ERROR messages from pip, and find out which dependency you are
missing. I did a (very complex) test case with Python 3.11.1 and the 0.28
klayout and everything worked as expected.
Best regards, Erwin

**Comment by klayoutmatthias** [comment]
With 0.28.2 there are Python 3.11 wheels available for MacOS, Linux and Windows. 

So no need to build from sources anymore :)

I'll close this ticket. If you see issues, feel free to open a new one.

Matthias
