### ISSUE TITLE
Additional LEF files in Reader Options of Technology Manager

### ISSUE THREAD

**Issue by stevvik** [KLayout/klayout#1257]
Hello!

For correct DEF visualization of my digital block I added LEF with standard cells in 
Reader Options->LEF/DEF->LEF+Macro Files->Additional LEF files
field in Technology Manager. Now DEF opens successfully.
But when I try to open another LEF file through File->Open, this added in Technology manager LEF is loaded too and conflicts with MACROs  defined in opening LEF, because it contains MACROs with the same names. And Klayout gives "Duplicated MACRO" error.

I think that additional LEF files defined in Reader Options are intended for DEF only and should not be opened when LEF view is opend.

**Comment by klayoutmatthias** [comment]
Please see https://github.com/KLayout/klayout/issues/1208

I think that is a misunderstanding. Right now, you cannot load LEF files at all. Only DEF is supported.

Matthias
