### ISSUE TITLE
I cannot setup a new package

### ISSUE THREAD

**Issue by mnaaom** [KLayout/klayout#1272]
I have defined the klayout salt mine environment variable (grain.xml)and extracted the package itself but klayout couldn't find the PDK
what should I do more ??

also it gives me this error at the beginning :

![Capture](https://user-images.githubusercontent.com/124269498/216336006-71480811-dab6-4642-9d5e-1e02b168540a.PNG)

**Comment by klayoutmatthias** [comment]
What exactly are you doing?

Did you take a look here: https://www.klayout.de/package_cookbook.html ?

Basically the environment variable points to an URL that delivers the package index - that is a listing of all available packages in XML format. grain.xml is a different thing. You need to provide this file when you register a package.

Matthias
