### ISSUE TITLE
macos and linux builds are not being built and uploaded to PyPI

### ISSUE THREAD

**Issue by joamatab** [KLayout/klayout#1280]
https://pypi.org/project/klayout/#files

![image](https://user-images.githubusercontent.com/4514346/216857344-6b7e1301-ddc1-44e6-8082-0a54ab609dfc.png)

It seems like no space left for the runners

![image](https://user-images.githubusercontent.com/4514346/216857388-c6bd1bd0-e56b-4588-89ac-4e5f7f43d62e.png)

@klayoutmatthias 
@sebastian-goeldi 
@thomaslima

**Comment by klayoutmatthias** [comment]
No real idea why Linux failed. I have restarted the build. Let's see what happens ...

**Comment by sebastian-goeldi** [comment]
That worked. Thank you Matthias!

**Comment by klayoutmatthias** [comment]
Exactly :) Some glitch I assume ... most times the builds work.
