### ISSUE TITLE
Layout diff should ignore shape or instance duplicates

### ISSUE THREAD

**Issue by klayoutmatthias** [KLayout/klayout#1281]
This is specifically useful if comparing OASIS vs. GDS. These files should basically be identical, but GDS may contain shape duplicates which in OASIS are usually removed as they cannot be represented as repetitions.

Shape duplicates are not considered a difference, so the diff should could duplicates as single shapes.

**Comment by stefanottili** [comment]
This did make it into the release, should be closed, no ?
