### ISSUE TITLE
zlib.h: No such file or directory

### ISSUE THREAD

**Issue by huangwenjunlovedy** [KLayout/klayout#1293]
![image](https://user-images.githubusercontent.com/20516638/219308243-0b0d5311-32aa-486d-aadc-8296703ec479.png)
![image](https://user-images.githubusercontent.com/20516638/219308349-4b291e23-b9ef-4c04-8917-8a5f908576a6.png)

During the compilation of kaylet, the file zlib. h is missing

**Comment by klayoutmatthias** [comment]
Exactly. Thanks @Kazzz-S 

On Ubuntu for example, the package is zlib-dev.

Please see here for the packages you need to install: https://www.klayout.de/build.html ("Building KLayout on Linux").

Matthias
