### ISSUE TITLE
Partial mode and "Instances" (general: "Select" filter is not applied in partial mode)

### ISSUE THREAD

**Issue by lizimeng996** [KLayout/klayout#1302]
When "Instances" is selected, I do not want pcells to be selected by PartialService.So how can I get whether instances are is_checked in PartialService?Can you give me an example? Thank you very much.

**Comment by klayoutmatthias** [comment]
Are you patching C++ code?

**Comment by lizimeng996** [comment]
Yes, I'm modifying the C++ code for some special needs. I want PartialSelect to be like MoveSelect. Pcell cannot be selected when instances are selected. But I don't know how to get the status of instances.

**Comment by klayoutmatthias** [comment]
I see your point. Partial mode does not consider the "Select" options. That is by design and there is no trivial solution to this problem.

You can keep this issue open and ask for a fix.
