### ISSUE TITLE
LEF/DEF topics

### ISSUE THREAD

**Issue by klayoutmatthias** [KLayout/klayout#1307]
This ticket is collecting some feedback regarding LEF/DEF implementation:

1. IOTIMINGS section needs to be parsed / skipped:

```
DESIGN test ;
IOTIMINGS 206 ;
- ( PIN a ) + RISE SLEWRATE 500 500 + FALL SLEWRATE 500 500 ;
- ( PIN b ) + RISE SLEWRATE 500 500 + FALL SLEWRATE 500 500 ;
- ( PIN c ) + RISE SLEWRATE 500 500 + FALL SLEWRATE 500 500
  + CAPACITANCE 250000 ;
END IOTIMINGS
END DESIGN
```

2. COMPONENTS + UNPLACED appears to potentially have a point and rotation in some flavors -> in that case, place it.

3. PIN labels are taken from NET, not PIN name

4. reading hierarchical def files (blending?) - If there is no lef MACRO for one of the def files, use the def DIEAREA bounding box instead of the lef SIZE/ORIGIN

NOTE: right now, KLayout does not support hierarchical DEF as is. 'blending' is an option to blindly merge files. The included files do now know about details of the cell calls and vice versa.

**Comment by stefanottili** [comment]
I just ran into the " + UNPLACED ( x y ) orient " components are dropped issue again.
It would be nice if strm2oas would issue a warning and that these as if they're + PLACED, + FIXED or + COVER

**Comment by klayoutmatthias** [comment]
I'm not sure if there is anything left. Close that issue?

**Comment by stefanottili** [comment]
Did you implement 1) ? 
ignore 4). There is a warning about missing lef, good enough.

**Comment by klayoutmatthias** [comment]
Right, IOTIMINGS is not implemented. I couldn't find a reference to that in the 5.8 doc.

Matthias

**Comment by stefanottili** [comment]
IOTIMINGS seem to be so ancient that this issue can be closed.
