### ISSUE TITLE
Klayout for ubuntu 22.04 arm64

### ISSUE THREAD

**Issue by risheb** [KLayout/klayout#1312]
Hi, I am trying to get latest klayout for ubuntu 22.04.2 arm64 version since I am running it on M1 MacBook Pro (2020). I am using virtual machine to to run ubuntu. Klayout 0.26 is too old for other software to use this. is there any deb release for arm64 version? I tried building it from source. I got the bin-release, but I am not able to install and run it. Please let me know if there any way to get the latest 0.28.5 klayout for ubuntu 22.04.2 arm64.

**Comment by klayoutmatthias** [comment]
No, there is not. At least not to my knowledge.

After all, providing the packages is a community effort. I don't own hardware to do that myself and petting CI bots is not my favorite spare time activity. 

But you can always build KLayout from source yourself. Provided Ubuntu on ARM is well maintained (as it is on x86), this process is pretty straightforward and should work with the recipes given here: https://www.klayout.de/build.html (scroll down to "Building KLayout on Linux").

Matthias

**Comment by risheb** [comment]
well, I am unable to install using that method since my ubuntu is arm64 version. Even if I run build.sh. without-qt I get following error
![image](https://user-images.githubusercontent.com/33462440/224462197-4be7fd68-5eb9-44b8-9d53-870d10567d02.png)

Rishab Baradwaj

**Comment by klayoutmatthias** [comment]
Looks like in your case you need to find the shared object version of libruby. Specify that version as the -rblib parameter of build.sh.

In my case that is:

```
build.sh -rblib /usr/lib/x86_64-linux-gnu/libruby-3.0.so 
```

**Comment by risheb** [comment]
Thanks, I am able to complete the code. can you help me on how to run the klayout? sorry I am new to this.

**Comment by risheb** [comment]
I figured out a way to run it from command line but I am still seeing below errors in terminal. 
![image](https://user-images.githubusercontent.com/33462440/224950128-70b476b9-9260-47f3-8359-d687352630d0.png)
![image](https://user-images.githubusercontent.com/33462440/224950283-c9942946-60bc-426f-a8b5-85cd855dabcb.png)
![image](https://user-images.githubusercontent.com/33462440/224950454-e6cb3745-5108-443b-93ac-e023efaed308.png)

the app loads after these errors though.

**Comment by klayoutmatthias** [comment]
In the sources you find a file `etc/klayout.desktop`. Copy that to `~/Desktop` and on the desktop right-click it a select "Allow Launching". It may not work out of the box unless you have include KLayout in PATH. In that case, you can specify the full path in the `Exec` field of `klayout.dektop`.

There are plenty of articles that explain this in more detail.

**Comment by risheb** [comment]
Thanks! it worked like a charm!
