### ISSUE TITLE
crash on linux system(CentOS Linux release 7.9.2009 (Core)).Is the cause the same as issue #1222?

### ISSUE THREAD

**Issue by lizimeng996** [KLayout/klayout#1316]
### The error code is as follows, and this code gets stuck in an infinite loop because polygon_contour_iterator it has an error in the loop. But I don't know what caused

last_pt is the begin of the vector.
pt is the end of the vector.

for (polygon_contour_iterator it = last_pt; it != pt; ++it) {                
                        out.push_back(*it);
 }

### The gdb debugging error information is as follows:
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff4ed4892 in db::point<int>::x (this=0xb6af000) at ../../../klayout/src/db/db/dbPoint.h:439
439	  return m_x;
(gdb) bt
#0  0x00007ffff4ed4892 in db::point<int>::x() const (this=0xb6af000) at ../../../klayout/src/db/db/dbPoint.h:439
#1  0x00007ffff4ed4d9a in db::point<int>::point(db::point<int> const&) (this=0x7fffffff9348, d=...) at ../../../klayout/src/db/db/dbPoint.h:84
#2  0x00007ffff4ee8070 in db::polygon_contour<int>::operator[](unsigned long) const (this=0xb2a5d00, index=527916) at ../../../klayout/src/db/db/dbPolygon.h:850
#3  0x00007ffff1885b7f in db::polygon_contour_iterator<db::polygon_contour<int>, db::unit_trans<int> >::operator*() const (this=0x7fffffff93e0) at ../../../klayout/src/db/db/dbPolygon.h:1174
#4  0x00007ffff1b77d83 in lay::SimplifyLayoutDialog::SimplifiedArcInPts(db::polygon_contour_iterator<db::polygon_contour<int>, db::unit_trans<int> >, db::polygon_contour_iterator<db::polygon_contour<int>, db::unit_trans<int> >, std::vector<db::point<int>, std::allocator<db::point<int> > >&, int) (this=0x7fffffffaeb0, begin=..., end=..., out=..., sides=8)
    at ../../../klayout/src/lay/lay/laySimplifyLayoutDialog.cc:930
#5  0x00007ffff1b77ee0 in lay::SimplifyLayoutDialog::SimplifiedArc(db::polygon<int>&, db::polygon<int>&, int) (this=0x7fffffffaeb0, in=..., out=..., sides=8)
    at ../../../klayout/src/lay/lay/laySimplifyLayoutDialog.cc:951；

(gdb) f 0
#0  0x00007ffff4ed41c2 in db::point<int>::x (this=0xb6aa000) at ../../../klayout/src/db/db/dbPoint.h:410
410	  return m_x;
(gdb) p m_x
Cannot access memory at address 0xb6aa000

**Comment by klayoutmatthias** [comment]
This is not a bug of KLayout, this is your code. Whatever "SimplifyLayoutDialog" does, it might give you a broken polygon object or the iterators are invalid or whatever.

If you did not do yet, please create a project fork and publish your changes there. I am willing to take a look then. But I do not appreciate users working on secret code and then asking me to debug. After all, KLayout C++ code is GPL and that comes with some obligations.
