### ISSUE TITLE
SPICE reader: support for .lib statement

### ISSUE THREAD

**Issue by klayoutmatthias** [KLayout/klayout#1320]
Please see the discussion here: https://www.klayout.de/forum/discussion/2253/resolving-lib-control-statements-in-spice-netlists#latest

A useful workaround is to use ngspice as a preprocessor.

**Comment by thesourcerer8** [comment]
I tried to use ngspice as a preprocessor, but I couldn't get it to work. Can you give an example how to do that for Sky130 examples?
