### ISSUE TITLE
Add Layout.each_shape

### ISSUE THREAD

**Issue by EugeneZelenko** [KLayout/klayout#1325]
Hi, Matthias!

It'll be nice to have `Layout.each_shape` like currently available `LayoutView.each_layer` to simplify loops over all shapes.

**Comment by klayoutmatthias** [comment]
Hi Eugene,

that's kind of difficult as there are multiple cells, so iterator has to traverse cells, hence needs to tell which cell it is in.

I wonder what the use case is.

Kind regards,

Matthias

**Comment by EugeneZelenko** [comment]
Hi, Matthias!

My idea was about API consistency, but I may be wrong with too simplistic understanding and could miss many complexities.

**Comment by klayoutmatthias** [comment]
I think that needs further elaboration. I'll close it for now. Please reopen when you have an opinion about specific details, e.g. how to indicate the cell a shape is in.

**Comment by ejprinz** [comment]
A shape is always in a cell, so I think the correct iteration is to first determine the cells (which can be done with the Layout class) and then iterate over these cells to fnd all shapes on all layers. I don't think it is needed to have the shapes know the cells they are in. GDSII does not need that.
