### ISSUE TITLE
Loading a lydrc file in KLayout via command line and open in UI

### ISSUE THREAD

**Issue by basnijholt** [KLayout/klayout#1342]
@klayoutmatthias, I am attempting to integrate my Python program with KLayout DRC, running in headless mode, to load a lydrc (report database) file, and open it the UI.

However, I haven't been able to find an option for loading a report database file using the command line. Does such an option exist?

_Context:_ The reason for running KLayout in headless mode is to enable automation and because we are manually (with code) extending the report database with annotations that were not created by KLayout itself (rather a different engine that can write valid report databases.)

**Comment by klayoutmatthias** [comment]
`.lydrc` is the DRC script (XML version). The report database (RDB) default extension is `.lyrdb`. 

The option to load it is `-m`:

```
klayout -h
...
-m <database file>  Load RDB (report database) file (into previous layout view)
...
```

Matthias
