### ISSUE TITLE
feature request: create a def single/mulitpart path import option

### ISSUE THREAD

**Issue by stefanottili** [KLayout/klayout#1345]
If there are multiple path segments on the same layer, klayout currently creates multiple two point path segments.
It used to write these as a single multi-point path. 
Please expose the single vs multipart path behavior as an def import option.

src/plugins/streamers/lefdef/db_plugin/dbDEFImporter.cc

 427 #if 0
 428         //  single path
...
 435 #else
 436         //  multipart paths

**Comment by klayoutmatthias** [comment]
The option is called "--lefdef-joined-paths" for strm* buddy tools
and "joined_paths" for pya/RBA.

Wires with multiple segments are combined into long paths when
possible - this fails on anisotropic widths and 45 degree segments.
