### ISSUE TITLE
Add application events for indicating start/finish of restoring session

### ISSUE THREAD

**Issue by EugeneZelenko** [KLayout/klayout#1349]
Hi, Matthias!

It'll be great to add `Application` events that indicate start/finish of restoring state . I'd like to tweak layout views loaded from session, so relevant callback could be installed/uninstalled easily. Alternative requires to keep track of all layout views.

**Comment by klayoutmatthias** [comment]
I have added two new events to `MainWindow` (because that is the object that does the session restore): `on_session_about_to_be_restored` and `on_session_restored`.

**Comment by EugeneZelenko** [comment]
Hi, Matthias!

Thank you for help!
