### ISSUE TITLE
Feature Request: AutoSave/Backup Gds

### ISSUE THREAD

**Issue by raphaelvalentin** [KLayout/klayout#135]
Hi, 
few times, I experienced some random crashes of klayout with Ubuntu Gnome 16. I would be very interested about an autosave or auto backup each n-minute form in preference.
What do you think about this feature?
Thank you very much,

**Comment by klayoutmatthias** [comment]
Hi,

I would be more interested to learn about the crashes. Anything particular about your configuration or special application?

Matthias
