### ISSUE TITLE
Instance Property form: Array Instance col/row would be more intuitive then the current row/col

### ISSUE THREAD

**Issue by stefanottili** [KLayout/klayout#1356]
In the current Instance Property form, the Array Instances entries are presented as rows/colums.
Please reverse this order, col/row (x, y) would be more intuitive..

It's also the order in which gds aref col/row number and coordinates are defined.
Oasis repetitions are defined as N-column (x) by M-row (y) dimensions.

**Comment by klayoutmatthias** [comment]
This is how the three places for arrays now look like:

![image](https://github.com/KLayout/klayout/assets/25720841/7826c81a-9056-46a6-af3f-0950b6fac4ca)

![image](https://github.com/KLayout/klayout/assets/25720841/433cd497-033c-4e9d-b460-362525fd21da)

![image](https://github.com/KLayout/klayout/assets/25720841/491ec410-c819-4756-934b-896dd9c00cb7)

**Comment by stefanottili** [comment]
great, 'now' as in 'upcoming', right ?
I find the col/row (x/y dimension) much more intuitive then today's master:
<img width="976" alt="image" src="https://github.com/KLayout/klayout/assets/25827408/e322c070-a6c8-49aa-9349-2851aeaf6c8d">

**Comment by klayoutmatthias** [comment]
Yes, "now" means "soon" :)
I want to finalize and push out 0.29. It has been in the oven for too long already :(
Matthias
