### ISSUE TITLE
"Sized" question

### ISSUE THREAD

**Issue by dsus4wang** [KLayout/klayout#1387]
Hi ,
I just found the "sized" command from GUI(edit -> selection -> size shapes) is different from that function in Polygon class.
![image](https://github.com/KLayout/klayout/assets/58458517/8066b5a1-86ed-4145-aa2f-881bf665415c)

It's obviously the former is better. Could you tell me how to make the former sized transformation in code?Thanks a lot

**Comment by dsus4wang** [comment]
The Picture:
1: the original polygon (has round corner)
2:using the GUI sized transformation
3: using the Polygon.sized() function

**Comment by klayoutmatthias** [comment]
The description of the "size" function explains that: https://www.klayout.de/doc-qt5/code/class_Polygon.html#method78. 
Another way is to use the "Region" class instead of "Polygon".
