### ISSUE TITLE
Copy layer name in Layers panel

### ISSUE THREAD

**Issue by nikosavola** [KLayout/klayout#1420]
Pretty small quality-of-life thing but today I tried to copy a layer name from the Layers panel but this is not supported.

I think it's worth adding if simple enough and doesn't clutter the context-menu too much.

**Comment by klayoutmatthias** [comment]
When you click "rename" you should get a small input box from where you can copy the name.

**Comment by nikosavola** [comment]
> When you click "rename" you should get a small input box from where you can copy the name.

I guess this is a good solution, thanks!
