### ISSUE TITLE
Python Binding / Layout / find_layer broken for layer "name"

### ISSUE THREAD

**Issue by ejprinz** [KLayout/klayout#1425]
The Python Binding function "find_layer" works for numeric (layer, datatype), for (const LayerInfo info), but not for (string name). Test case:

```python
# Test case for 23/07/18 bug report
# 
import klayout.db as kl

lyo = kl.Layout()
l1 = lyo.layer(1, 0, 'L1;D0')

print(f'Layer Infos: {lyo.layer_infos()}')

print(f'Find layer by layer/datatype: {lyo.find_layer(1, 0)}')
print(f'Find layer by layer info: {lyo.find_layer(lyo.layer_infos()[0])}')
print(f'Find layer by layer name: {lyo.find_layer("L1;D0")}')
```

results in:

```sh
Layer Infos: ['L1;D0' (1/0)]
Find layer by layer/datatype: 0
Find layer by layer info: 0
Find layer by layer name: None
```

It would be good to have this working to be able to determine whether a layer of a certain name is in the layermap.

**Comment by klayoutmatthias** [comment]
It's not "broken", it's the way it is defined now.

![image](https://github.com/KLayout/klayout/assets/25720841/1c2a2360-9018-4908-a3c1-5671377127c1)

Right now, a layer is either numbered or named. If numbered, the name is a secondary information. So numbered layers can be found by number, named layers by name.

```
bool 
LayerProperties::log_equal (const LayerProperties &b) const
{
  if (is_null () != b.is_null ()) {
    return false;
  }
  if (is_named () != b.is_named ()) {
    return false;
  }
  if (is_named ()) {
    return name == b.name;
  } else {
    return layer == b.layer && datatype == b.datatype;
  }
}
```

Problem is the strict weak ordering which is needed for efficient layer table lookup:

```
bool 
LayerProperties::log_less (const LayerProperties &b) const
{
  if (is_null () != b.is_null ()) {
    return is_null () < b.is_null ();
  }
  if (is_named () != b.is_named ()) {
    return is_named () < b.is_named ();
  }
  if (is_named ()) {
    return name < b.name;
  } else {
    if (layer != b.layer) { return layer < b.layer; }
    return datatype < b.datatype;
  }
}
```

Ordering (or hashing) is difficult if you consider fallback comparison criteria.

Matthias
