### ISSUE TITLE
Add option to filter out geometric primitives from Marker Database Browser Info widget

### ISSUE THREAD

**Issue by EugeneZelenko** [KLayout/klayout#1430]
It makes sent to have possibility to  filter out geometric primitives (included in `value`) from Marker Database Browser Info widget. Main purpose of geometrical primitives is to show them in layout view and they only interfere with `text`.

**Comment by klayoutmatthias** [comment]
The solution is a new switch here:
![image](https://github.com/KLayout/klayout/assets/25720841/e6d00a87-1575-4bea-844b-387e5e8f4160)

When unchecked, shapes are not listed:
![image](https://github.com/KLayout/klayout/assets/25720841/da60aab9-6e6b-46b3-900f-fe47a00bee78)

The setting is persisted and can be configured through the "rdb-list-shapes" configuration property.

**Comment by EugeneZelenko** [comment]
Hi, Matthias!

Thank you for fast implementation! But could this setting be controlled via configuration and be persistent there?
