### ISSUE TITLE
Support for label position in Marker Database Browser

### ISSUE THREAD

**Issue by EugeneZelenko** [KLayout/klayout#1441]
It'll be great to add support for label position as in GDS format ("n/e/s/w" and their combinations) in Marker Database Browser, so multiple labels could be shown for single violation without using `\\n` in label text.

**Comment by EugeneZelenko** [comment]
Hi, Matthias!

Sure, `halign` and `valign` should be enough. But does `rdb` reader support them? I looked on `_test_extractor_impl` for `Text/DText` and it seems to read only text and transformations, but not alignments.

**Comment by klayoutmatthias** [comment]
You're right. That's not supported currently.

Matthias

**Comment by EugeneZelenko** [comment]
Hi, Matthias!

Thank you for such fast implementation!

**Comment by nmz787-intel** [comment]
Is this related to text Labels not showing rotation? I see my labels rotated in Calibre, but not KLayout.

**Comment by EugeneZelenko** [comment]
Not, it was about text alignment relative to reference point (above/below/center and left/right/middle). See changes that fixed issues, especially test case.
