### ISSUE TITLE
Zoom (in) function with selected layers significantly slower in newer releases

### ISSUE THREAD

**Issue by matthias-vorwerk** [KLayout/klayout#1453]
When compiling and using latest klayout release 0.28.10 and opening a larger layout  the right mouse zoom in function, but also keyboard based zoom in functionality has longer delays.

CentOS7, self compiled QT5 + klayout 0.28.10, removed $HOME .klayoutrc 

The effect is as follows:
- open a large layout
- full hierarchy depth (*)
- show only one selected layer, then add a second layer to show 
- try to zoom in  (and out + in again, several times)

now: when zooming in often the zoom in shows significant delays.
**BUT** When I **Show All** layers. there is no such a delay. Showing only 2..3 individual layers again shows the zoom in issue.
This is very reproducible with different layouts, uncompressed GDS sizes used for tests: 3..5 GB

Then I compiled previous releases and it looks like this is happening since klayout 0.28.8.
It still works fine in 0.28.7.

**Comment by klayoutmatthias** [comment]
Thanks for reporting this problem.

I could reproduce and fix it - it was actually related to the mouse hover event and it was related to the change in the text box treatment. The search for the mouse hover was going too deep.

Thanks and best regards,

Matthias
