### ISSUE TITLE
strm2oas: def path with first/last segment length < halfwidth are read wrong

### ISSUE THREAD

**Issue by stefanottili** [KLayout/klayout#1472]
strm2oas by default decomposes multi-point path with first or last segment length < halfwidth incorrectly.
They are read correctly as multi-point path by using the --lefdef-joined-paths option.

make bad; make xor   shows the difference
make good; make xor  doesn't

[test_spnet.tgz](https://github.com/KLayout/klayout/files/12547728/test_spnet.tgz)

**Comment by klayoutmatthias** [comment]
Thanks! Perfect testcase preparation!

But hard to fix :(

**Comment by klayoutmatthias** [comment]
I mean, I don't know if the "good" version is even correct - that assumes a "GDS style" interpretation of path. Can you confirm the way these paths are build is compatible with other tools?

Like this "good" path:

![image](https://github.com/KLayout/klayout/assets/25720841/8e57325c-fb8b-4d4f-b588-f1b42b1d48d0)

**Comment by stefanottili** [comment]
It certainly looks like unintended,  but was found in the wild.I would say the fix is to warn about it and not break it into two point path.The multipoint path is handled correctly after all.I have an option to turn this into a polygon, because somebody got burned somewhere years ago by some tool not doing the right thing ….On Sep 7, 2023, at 15:48, Matthias Köfferlein ***@***.***> wrote:﻿
I mean, I don't know if the "good" version is even correct - that assumes a "GDS style" interpretation of path. Can you confirm the way these paths are build is compatible with other tools?
Like this "good" path:

**Comment by klayoutmatthias** [comment]
Okay ... my fix now is to join the first two segments if the initial segment is too short. Same for the last two segments. 

Matthias

**Comment by stefanottili** [comment]
more elaborate then what I would have done, but I'll take it.
I would be nice to get a warning about this situation.
