### ISSUE TITLE
Ignore "Summarize missing layers" when sending XOR result to other layout

### ISSUE THREAD

**Issue by 3e4** [KLayout/klayout#1473]
Hi,

I use klayout extensively for my work, but came accross a behavior that I think can be improved.
With the shown settings, the generated "other layout" does not contain any shapes in the XOR, when the layer is missing in one of the layouts. I would suggest to ignore the "Summarize missing layers" function when sending to "other layouts". For sending output to marker database, this function works wonderfully!

Thank you

![image](https://github.com/KLayout/klayout/assets/7106945/6a0be4d4-a35e-4e4c-bebc-2af2e59b21df)

**Comment by klayoutmatthias** [comment]
0.28.12 is released :)

This should earn me a coffee, doesn't it?
