### ISSUE TITLE
documentation typo: drc_runsets, Objects and methods, Boolean operations: "+ (xor), join" -> "+ (join)"

### ISSUE THREAD

**Issue by sto6** [KLayout/klayout#1511]
Typo suspected in on-line documention:
https://www.klayout.de/doc-qt5/manual/drc_runsets.html#h2-312

section: Objects and methods

text says (neglecting the hyperlinks here):
```
* Boolean operations:
   & (and), | (or), - (not), ^ (xor), + (xor), join
```

the 2nd "xor" (after +) looks incorrect. Possibly it should be?:

`   & (and), | (or), - (not), ^ (xor), + (join)`

**Comment by klayoutmatthias** [comment]
Thanks, easy to fix :)
