### ISSUE TITLE
Marker Database Browser: add context menu to `Info` widget

### ISSUE THREAD

**Issue by EugeneZelenko** [KLayout/klayout#1527]
Hi, Matthias!

It'll be great to add context menu to `Info` widget in `Marker Database Browser` with `Select All` and `Copy` commands (later state should depend on text selected or not). Keyboard shortcuts (`Ctrl+A`  and `Ctrl+C`) work, but it's not obvious that they are available.

Also `Select All` command should be added to `Directory` and `Markers` widgets context menu (`Ctrl+A` works).

**Comment by klayoutmatthias** [comment]
I think that is easy :)
