### ISSUE TITLE
KLayout crashing with two consecutive calls of the same LayoutView::show_layout command 

### ISSUE THREAD

**Issue by rizoschrist** [KLayout/klayout#1533]
Klayout (v0.27.7) is crashing with the following error message when I execute the following command two times in a row:

pya.Application.instance().main_window().current_view().show_layout(layout, False)
pya.Application.instance().main_window().current_view().show_layout(layout, False)

![error image](https://github.com/KLayout/klayout/assets/29468900/642d53f6-d001-4d36-a942-170d51004b14)

ERROR: ../../../src/laybasic/laybasic/layCellTreeModel.cc,444,! mp_layout->under_construction () && ! (mp_layout->manager () && mp_layout->manager ()->transacting ())
ERROR: Exception caught: Internal error: ../../../src/laybasic/laybasic/layCellTreeModel.cc:444 ! mp_layout->under_construction () && ! (mp_layout->manager () && mp_layout->manager ()->transacting ()) was not true

PS: minor but.. same layers' colors keep changing each time I execute the above command, which becomes troublesome to id the layers in a dense layout

**Comment by klayoutmatthias** [comment]
Please check with the lastest version. 0.27.7 is very old.

**Comment by klayoutmatthias** [comment]
Also reproducible on 0.28.12 and fixed.

Again, I'd appreciate if a bug report refers to the current version.

**Comment by rizoschrist** [comment]
I can verify resolution in v0.28.13
