### ISSUE TITLE
Layout::dup does not copy properties

### ISSUE THREAD

**Issue by rizoschrist** [KLayout/klayout#1534]
The following code does not work (KLayout v0.27.7):

```
layout = pya.Layout()
layout.set_property("key", "value")
layout_dup = layout.dup()
layout_dup.property("key") # returns None
```

**Comment by klayoutmatthias** [comment]
Again, please check with the latest version which is 0.28.12.

**Comment by klayoutmatthias** [comment]
Reproducible on 0.28.12 and fixed.

I'd appreciate if you confirm that a problem exists on the latest version.
