### ISSUE TITLE
Misleading description in "Flatten Cell"

### ISSUE THREAD

**Issue by Jebearssica** [KLayout/klayout#1539]
Hi Matthias:

Currently, I'm trying to flatten a cell into its parent cell and I find that in [doc](https://www.klayout.de/doc-qt5/manual/flatten.html#k_1) "Flatten Cell" is able to do that. However, I tried in version 0.28.12, but the results show that "Flatten Cell" tries to pushing all its' child instances into selected Cell rather than the description in document.
I'm wondering if there's any misunderstanding?

Victor

**Comment by klayoutmatthias** [comment]
No, you're right. The cell's "flatten" does not behave like explained. It will make the cell flat, but not remove it. 

If you want the behavior as described, you can use this custom query in "Edit/Search and Replace":

```
with instances of cell CHILD do inst.flatten
```

(replace CHILD by the name of the cell you want to flatten).

Matthias
