### ISSUE TITLE
latest klayout python release failing to install on windows

### ISSUE THREAD

**Issue by joamatab** [KLayout/klayout#1548]
Some gdsfactory users are reporting that the latest klayout 0.28.13 can't be installed on windows using `pip install klayout`

https://github.com/gdsfactory/gdsfactory/issues/2328#issuecomment-1828009539

**Comment by klayoutmatthias** [comment]
Hi @joamatab

Delivery of the Windows packages was delayed because I was not owning the credentials on the Azure pipeline and they had expired. I had to push the packages manually which I did yesterday.

Could you check if the problem still persists?

Thanks,

Matthias

**Comment by klayoutmatthias** [comment]
BTW: PyPI deployment is a permanent troublemaker. Maybe fixing your dependency to a verified release instead of the latest one makes life somewhat easier.

Matthias

**Comment by joamatab** [comment]
yes, we can pin the klayout version on gdsfactory side

I tested and it works

![image](https://github.com/KLayout/klayout/assets/4514346/e306ad34-3cae-4a15-a40c-6ac4be1e7cfe)


@tvt173
