### ISSUE TITLE
Strange behaviour of KLayout 0.28.13

### ISSUE THREAD

**Issue by ashkanr65** [KLayout/klayout#1559]
I'd like to report a possible bug in KLayout 0.28.13. I am not sure if it is related to my version, but I tried it on version 0.28.5 and it works fine. The problem occurs when I try to move an object with the Movements setting in Diagonal mode. **I cannot move the object to any angle between 90 and 180 degrees or between 270 and 360 degrees. If I try to do so, the object’s movement will be mirrored on the X-axis.** Could you please check on this issue and let me know if there is a solution?

Another issue that I have noticed is that when I try to move an array of objects by clicking on the desired location, they will suddenly jump to a different place.

I have found another strange behavior when I use a Pcell and then flatten it. If I modify anything on that specific Pcell in its layout, all other Pcells also change accordingly!

**Comment by klayoutmatthias** [comment]
Please take a look into "View" menu - I think you have "Select Top Level Objects" OFF. In that case, you can select objects inside the hierarchy and if you modify them, other instances of the cell you modified will change accordingly.

This mode is called "Edit in Place" in Cadence.

If you find that confusing, you should make it a habit to turn on "Select Top Level Objects". In that case, you can only select object on the top level cell and you will not see these effects.

Matthias

**Comment by klayoutmatthias** [comment]
The first topic should be fixed in 0.28.14. The other ones I'd like to have more information about.

**Comment by ashkanr65** [comment]
Hi Matthias,
Sorry for the late reply. Regarding this issue: 
“Another issue that I have noticed is that when I try to move an array of objects by clicking on the desired location, they will suddenly jump to a different place.” 
This sometimes happened to me too. I tried to regenerate it but I couldn’t. So it was probably something related to my computer, I hope. 
Regarding this one: 
“I have found another strange behavior when I use a Pcell and then flatten it. If I modify anything on that specific Pcell in its layout, all other Pcells also change accordingly!”

To see this, you can: 
1- Generate an array of Circle from Basic library (Basic.CIRCLE). 
2- From Edit menu, Layout, Convert All Cells to Static. 
3. Try to move one of the circles. All of them will move with the one. 
5. In this example, since circle is a very simple object, you cannot edit the shape. But if you use a text and edit it (remove one of the words), you will see all of the objects will remove that word.

I hope I explained it well.

**Comment by klayoutmatthias** [comment]
No worries, thanks for the update.

For the PCell problem: if by "array" you mean an array of cells like this:

![image](https://github.com/KLayout/klayout/assets/25720841/28a5917a-51d6-4268-8590-15c5328b52d9)

then the explanation is, that if you convert the cell to "static cell", the array still remains one. So in my case I have 4 x 4 = 16 instances of the same cell and changing one will change all the others.

If you want all instances to become individual variants of the PCell, you first have to resolve the array into single instances using "Edit/Selection/Resolve Arrays". If you then convert these instances into static cells, each instance becomes its own cell.

Matthias
