### ISSUE TITLE
Build with Qt6

### ISSUE THREAD

**Issue by Yaraslaut** [KLayout/klayout#1561]
By default only qt5  detection exist inside `build.sh` script, see
https://github.com/KLayout/klayout/blob/5b4473e37c33a8eb1bd94b7c86b0a0035b0b1b9e/build.sh#L301

So to build with Qt6 I had to add `qmake6` for my system inside the list. 

Also, as a side note, is there any plans to migrate to cmake ?

**Comment by klayoutmatthias** [comment]
You can always specify your qmake version on "build.sh":

```
build.sh -qmake qmake6
```

And no, I don't want to migrate to cmake. You can generate cmake from qmake if you want.

**Comment by Yaraslaut** [comment]
> You can always specify your qmake version on "build.sh":
> 
> ```
> build.sh -qmake qmake6
> ```
> 
> And no, I don't want to migrate to cmake. You can generate cmake from qmake if you want.

Thanks for the quick reply.
I was a bit confused when i saw that the script decided to use qt5 instead of qt6 while in the description I see : `Plain building for Qt4, Qt5 and Qt6 (one Qt version installed)`  however the script  does not check whether qt6 is present on the system so i wanted to bring this to your attention.

**Comment by klayoutmatthias** [comment]
In most distros, if you have either Qt4, 5 or 6 installed, "qmake" alone will do. There is no need to check for a specific qmake6 etc. This appears to be kind of special in your case. What is your distribution?

Matthias

**Comment by Yaraslaut** [comment]
> In most distros, if you have either Qt4, 5 or 6 installed, "qmake" alone will do. There is no need to check for a specific qmake6 etc. This appears to be kind of special in your case. What is your distribution?
> 
> Matthias

This is on Arch, 
from package info i see that `qt5-base` package `/usr/bin/qmake` and `/usr/bin/qmake-qt5` 
while `qt6-base` package `/usr/bin/qmake6` 
and for the reference qmake6 package for ubuntu 22.04 https://packages.ubuntu.com/jammy/amd64/qmake6/filelist 
also `/usr/bin/qmake6`

**Comment by klayoutmatthias** [comment]
I see. Qt6 goes different ways than "qtchooser" which was in place for Qt4 and Qt5. But anyway, I can't anticipate all names people come up for "qmake". So please simply use "-qmake". 

Matthias
