### ISSUE TITLE
Duplicated Tabs in the Macro Development Tool

### ISSUE THREAD

**Issue by Kazzz-S** [KLayout/klayout#1563]
Some tabs are duplicated in the Macro Development tool window.

**KLayout Version 0.28.12**
![Linux-src02812](https://github.com/KLayout/klayout/assets/16847255/58827d56-6871-48ce-9331-4559738d2b5d)
![Mac-dmg02812](https://github.com/KLayout/klayout/assets/16847255/a12a0b6e-6afe-4f67-957c-41914ca9b2d5)
![Windows-bin02812](https://github.com/KLayout/klayout/assets/16847255/354a82bb-f9b5-4433-bfcb-bc4f93a80af1)

----

**KLayout Version 0.28.13**
![Linux-src02813](https://github.com/KLayout/klayout/assets/16847255/e0dd9e84-49e7-477f-991f-d86dd0def8be)
![Mac-dmg02813](https://github.com/KLayout/klayout/assets/16847255/d7baa857-1be2-4a39-986f-16bb746f4fae)
![Windows-bin02813](https://github.com/KLayout/klayout/assets/16847255/b9a72a98-0ddb-40fa-916f-67b84aaca225)

**Comment by klayoutmatthias** [comment]
Your right. Strange I did not notice.

There does not seem to be a negative effect, but it's ugly. I'll fix that.

Thanks,

Matthias

**Comment by Kazzz-S** [comment]
I have confirmed the fix; thank you very much :-)

![Mac-dmg02814](https://github.com/KLayout/klayout/assets/16847255/5221e9c9-7a0d-4d9b-b359-f60847581c71)
