### ISSUE TITLE
Make "toggle (selected) layer" key-bindable

### ISSUE THREAD

**Issue by 3e4** [KLayout/klayout#1569]
Hi,

after using klayout a lot to look at complex layouts, I have some usability ideas I want to share and would be happy if they are considered for implementation.

- Double-clicking a layer will toggle visibility. This is not key-bindable. Make it key-bindable.
- Have a new layer visibility option "toggle selected", which will read current state for each selected layer/group and invert it. Make it key-bindable.

Thank you!

**Comment by klayoutmatthias** [comment]
This is worth a coffee - and next time not the one that is paid from my own bonus points!

**Comment by klayoutmatthias** [comment]
Added my favorite other feature: "visibility follows selection"

**Comment by Kazzz-S** [comment]
Hello @klayoutmatthias,

I like the **visibility follows selection** feature! It's like the Bookmarks feature.
![T1569-still](https://github.com/KLayout/klayout/assets/16847255/30769efe-5a05-4de2-96a8-9602ed4497e1)
[ An MP4 movie: T1569.mp4.zip](https://github.com/KLayout/klayout/files/13682278/T1569.mp4.zip)

* The first half part of the movie: **UP/DOWN key** only
* The second half part of the movie: **Shift+UP/DOWN key**

Best regards,
Kazzz-S

**Comment by klayoutmatthias** [comment]
I honestly don't know why I did not come up with the "visibility follows selection" feature earlier. 

But thanks go to @3e4 who keeps bugging me about such features ;)

Matthias
