### ISSUE TITLE
Missing strm2*.exe in the Windows portable binary package (*.zip)

### ISSUE THREAD

**Issue by Kazzz-S** [KLayout/klayout#1578]
The portable binary package, `klayout-0.28.14-win64.zip`, does not include the buddy command line tools (**strm2\*.exe**).

However, the installer, `klayout-0.28.14-win64-install.exe`,  deploys these tools as expected.
![klayout-0 28 14-win64-install](https://github.com/KLayout/klayout/assets/16847255/03271648-aa40-4e70-80d2-0f3409c4cdb3)

**Comment by klayoutmatthias** [comment]
@Kazzz-S Thanks for noting that. I think the strm*.exe never were part of the .zip file, but that is easy to fix.

Best regards,

Matthias
