### ISSUE TITLE
Text display issues

### ISSUE THREAD

**Issue by Trabbish** [KLayout/klayout#1584]
Klayout version is 0.28.14, and in the setup window a part of the word has a large and small letter spacing. The same thing happens in the main screen under the Cells Views.
![image](https://github.com/KLayout/klayout/assets/40230291/4a3a9fdc-f194-4c7c-a1b2-bdf66beee842)
![image](https://github.com/KLayout/klayout/assets/40230291/bc08b5b0-714b-49c1-be0a-6e69f3c3bb72)

**Comment by Kazzz-S** [comment]
In my environment...
![Win10](https://github.com/KLayout/klayout/assets/16847255/b3e896aa-f075-4e10-b487-8b4bbceeb6cc)
![Linux](https://github.com/KLayout/klayout/assets/16847255/9fe27d40-274a-483d-9d4f-202b611e91a1)
![Mac](https://github.com/KLayout/klayout/assets/16847255/cad0e553-fcfd-4153-9f54-ee37297a831b)

**Comment by Trabbish** [comment]
Thank you, this issue is caused by win11
