### ISSUE TITLE
strm2*.exe files do not run in the Windows Command Shell and Power Shell

### ISSUE THREAD

**Issue by Kazzz-S** [KLayout/klayout#1589]
Hello @klayoutmatthias,

Thanks for fixing issue #1578.
Unfortunately, these Buddy tools, including those built locally from source, do not run in the Windows Command Shell and Power Shell.
However, **`they can run in a MinGW64 terminal`**. That is, they are not portable.

I guess that they were built as GUI applications, as shown below.
![buddy-exe](https://github.com/KLayout/klayout/assets/16847255/dd3ae7d4-bfd3-4a63-afaf-7641464f5784)

They should have been built as console applications, like
![console-exe](https://github.com/KLayout/klayout/assets/16847255/d87bbd24-869b-4cc1-844d-dc195e4f474a)

A change I made many years ago may be related to this issue.
![config](https://github.com/KLayout/klayout/assets/16847255/f3413a36-5ef5-47a9-89d9-1485f8751f27)

I'm going to test with:

```
win32 {
    CONFIG += console
}
```

Best regards,
Kazzz-S

**Comment by klayoutmatthias** [comment]
Hi @Kazzz-S,

you're right, but I am not sure if that actually is bad.

From what I see, the strm* utilities basically work also from cmd.exe, but the output is not visible. You can however, redirect the output to a file or pipe, like this:

```
strm2gds -h | more
```

I recall that console applications open their own console window when run from outside the shell - which is kind of ugly. I am sure it is possible to suppress this behavior in some way, but my experience dates back to a time when this wasn't the case. 

Matthias

**Comment by Kazzz-S** [comment]
Hi @klayoutmatthias,

I have confirmed that the ` | more` pipe works. Thanks for the clarification.

----

I also tested my idea above, and it looks OK, as shown in the five pictures below.
Please note that I have tested `$ ./scripts/deploy-win-mingw.sh  -64` only.

**[Chages]**
![1-config-console](https://github.com/KLayout/klayout/assets/16847255/ceb63892-405b-4f11-a6e7-efcc724dfe7b)

**[GUI ---> console]**
![2-buddy-exe-console](https://github.com/KLayout/klayout/assets/16847255/3e5170e4-7aba-472d-b4b4-1729c9b163c0)

**[In the MinGW64 Terminal]**
![3-mingw64-terminal](https://github.com/KLayout/klayout/assets/16847255/2dc7b172-6962-4d80-ac6e-6cc888d8687e)

**[In the Windows Power Shell]**
![4-power-shell](https://github.com/KLayout/klayout/assets/16847255/92c35883-a4a7-464f-91a1-cdc8267aa7b2)

**[In the Windows Command Shell]**
![5-command-shell](https://github.com/KLayout/klayout/assets/16847255/180fa058-cb61-4181-96dd-c87b40bf0ef0)

Regards,
Kazzz-S

**Comment by klayoutmatthias** [comment]
Hi @Kazzz-S,

I verified that "CONFIG += console" actually fixes the problem.

However, if I start the "strm*" tools as a subprocess from a GUI application, for example from KLayout's IDE console:

```
> import subprocess
# Change to your path:
> inst = "c:\\msys64\\home\\matth\\klayout\\build-release-win64"
> print(subprocess.check_output([inst + "\\strmrun", "--version"]))
```

then I see a console window flashing open briefly. This is the behavior I remembered and which I consider somewhat ugly. Someone running the strmxxx tools as subprocesses from his application - for example to do layout processing in the background - cannot stop these windows from popping up.

With a GUI application this isn't happening. In the past, I have not found a way to suppress this behavior. 

Matthias

**Comment by Kazzz-S** [comment]
Hi @klayoutmatthias,

To be honest, I had never imagined a use case like the example above. If you have that kind of background, I think building them as GUI applications is fine. I think it would be nice if there was a cautionary document somewhere (if it doesn't exist) about how to use a PIPE when using a strmxxx alone in a command shell.

Kazzz-S

**Comment by Kazzz-S** [comment]
Question resolved and closed.
