### ISSUE TITLE
dxf file parsing error, about spline curve，v2.0

### ISSUE THREAD

**Issue by libaineu2004** [KLayout/klayout#1592]
I submitted an issue before, here: https://github.com/KLayout/klayout/issues/1422

Today I discovered several dxf file parsing errors.
https://github.com/libaineu2004/myepolltest/releases/download/20240113/Drawing1.dxf
https://github.com/libaineu2004/myepolltest/releases/download/20240113/Drawing19.dxf

When parsing the file, Drawing1.dxf, there will be some extra straight line segments.
qcad:https://www.qcad.org/en/
![Snap3](https://github.com/KLayout/klayout/assets/11898277/2fb6cdd8-8cfd-4183-a207-6ac42bf6ce86)

klayout v0.28.11:
![Snap2](https://github.com/KLayout/klayout/assets/11898277/1debbbdb-d85a-4fe8-b9a4-88dc01ff0d00)

**Comment by klayoutmatthias** [comment]
Hi @libaineu2004,

thanks for reporting the issue.

The problem goes away in my case when I set the arc interpolation accuracy to 0.02 DXF units. I suspect that the input file contains some spline segments with extreme curvature and that this screws up numerics.

Matthias
