### ISSUE TITLE
Technology-specific Default Grids

### ISSUE THREAD

**Issue by Kazzz-S** [KLayout/klayout#1625]
Original Post => https://www.klayout.de/forum/discussion/2459/

This enhancement feature does not seem to be included in `0.28.16`.
Please include it in a future release :-)

I manually merged the `tech-specific-grids` branch into `0.28.16` on Linux and found it OK.
![0 28 16-f2459](https://github.com/KLayout/klayout/assets/16847255/2b2a0876-a15a-44f9-9f46-035c92a893fe)

Best regards,
Kazzz-S

**Comment by klayoutmatthias** [comment]
Oh, I'm terribly sorry ... I simply forgot that :(

I will make a new release quickly.

Matthias

**Comment by Kazzz-S** [comment]
Thank you very much. But I'm sorry I seemed to have rushed you.

Kazzz-S

**Comment by klayoutmatthias** [comment]
No worries, you did not rush me! :)

I just lost track of the many open topics. I should have created a ticket for tracking.

But I hope 0.28.17 is now fixing this. Last thing I had to add was scripting support for the new technology attribute, so the feature is complete now.

Best regards,

Matthias

**Comment by Kazzz-S** [comment]
Thanks a lot for releasing 0.28.17.
I'm building that version on macOS, as usual. **The 1st set on Monterey is over**.
![0 28 17-mac](https://github.com/KLayout/klayout/assets/16847255/748f0c5d-242b-4be3-906d-ad7850ab0fc7)

Best regards,
Kazzz-S
