### ISSUE TITLE
ERROR: Failed building wheel for klayout

### ISSUE THREAD

**Issue by planckian** [KLayout/klayout#1653]
When running `pip install klayout` on my Windows 11 machine with Python 3.12 I get the following error:

![Screenshot 2024-03-11 101204](https://github.com/KLayout/klayout/assets/160117585/c131f096-b787-4a5c-a9a8-1b33961bda6e)

I've tried installing older versions of KLayout all the way down to 0.28.1, but I always get the same error. I've also tried installing a few different versions of Microsoft Visual C++ (14.38 and 14.32), but that didn't help. Anyone has a tip on how to solve this issue? Many thanks.

**Comment by klayoutmatthias** [comment]
Python 3.12 isn't supported by the wheel files on Windows right now. Currently, up to Python 3.11 is supported.

If you can, please use Python 3.11.

I can try to enable 3.12 for 0.28.17, but thanks to the restrictive update policy of PyPI there is no guarantee.

Matthias

**Comment by klayoutmatthias** [comment]
Azure made me new wheels for Python 3.12 for win32 and win64, so you should be able to install the package now without building yourself.

Matthias

**Comment by planckian** [comment]
Thanks!
