### ISSUE TITLE
'Visibility Follows Selection' option for the 2.5d view

### ISSUE THREAD

**Issue by Kazzz-S** [KLayout/klayout#1666]
This is a feature request.
It would be nice if the 2.5d view had the 'Visibility Follows Selection' option.

![FeatureRequest](https://github.com/KLayout/klayout/assets/16847255/469cce4c-1927-4411-9e2e-fac4fab2ffd5)

Thanks
Kazzz-S

**Comment by klayoutmatthias** [comment]
Good point :)

As I am about to finish 0.29, I will schedule that feature for 0.29.1.

Best regards,

Matthias

**Comment by Kazzz-S** [comment]
Hi @klayoutmatthias,

Thank you for implementing the new feature, which I have successfully verified on Linux.

Best regards,
Kazzz-S

**Comment by klayoutmatthias** [comment]
Thanks as well for your feedback! :)

Matthias
