### ISSUE TITLE
[Qt6] QRegExpValidator class

### ISSUE THREAD

**Issue by Kazzz-S** [KLayout/klayout#1680]
This is an enhancement request regarding migration to Qt6.

The class 'QRegExpValidator' is not included in PYA so far.
![Image-01](https://github.com/KLayout/klayout/assets/16847255/8c3b5d03-e54f-487a-80f7-a1ee05386396)

I would also like to have it in the Qt6 environment since I use it to validate an IP address, as shown below.

https://github.com/KLayout/klayout/assets/16847255/ebe2c5c0-0310-4aea-b619-8c848472f053

Best regards,
Kazzz-S

**Comment by klayoutmatthias** [comment]
Hi @Kazzz-S,

Qt added `QRegularExpressionValidator` in Qt5 (leaving `QRegExpValidator`), but removed `QRegExpValidator` in Qt6. 

I'm afraid you will need to migrate to `QRegularExpressionValidator` for Qt6 compatibility. My understanding is that both are pretty much the same.

Best regards,

Matthias

**Comment by Kazzz-S** [comment]
Hello @klayoutmatthias,

Thanks for the info.
I should have searched the assistant document more carefully.
With the following changes, the tool works fine in both Qt5 and Qt6 environments.
![Image-03](https://github.com/KLayout/klayout/assets/16847255/c2d07bd2-2b9f-4be8-9d5e-e99453799946)

Best regards,
Kazzz-S
