### ISSUE TITLE
Does it help? 2.5d view on OpenGL 3.0

### ISSUE THREAD

**Issue by klayoutmatthias** [KLayout/klayout#1700]
In order to deal with a number of reports I received with respect to non-functional 2.5d views, I ported the view to GLSL 1.20 and removed the geometry shader. It should be compatible with OpenGL 3.0 now.

I have some hope this fixes the issue on MacOS.

The code is in the `d25view-fixing` branch (https://github.com/KLayout/klayout/tree/d25view-fixing). 

It could use some memory optimization, but first I would like to have some feedback. 

If you want to help, please give it a try and let me know if your 2.5d problem is fixed.

Thanks and best regards,

Matthias

**Comment by klayoutmatthias** [comment]
No, you don't :)

Looks like there is a bug in my shader program. Interestingly it compiled on Linux.

Matthias

**Comment by Kazzz-S** [comment]
Hello @klayoutmatthias,

Thanks a lot for trying to fix this issue.
I built the `d25view-fixing` branch on **macOS Monterey** (Intel Mac).

First, I got a syntax error relating to ";" but you have already fixed it.
![test-1](https://github.com/KLayout/klayout/assets/16847255/472fc376-8319-4b67-a8bb-5716368cbb83)

Next, I got some compilation errors at runtime.
![test-2](https://github.com/KLayout/klayout/assets/16847255/9209a818-1e4b-4deb-882f-68798222b851)

I've modified the code as below.
![test-3](https://github.com/KLayout/klayout/assets/16847255/19966275-9ec6-4170-8ca5-b0be766b1a16)

Then, I could successfully get the 2.5D view. (Also refer to #1569)

https://github.com/KLayout/klayout/assets/16847255/39d59f8b-72e0-406f-8252-b7d6996c709a

Best regards,
Kazzz-S

**Comment by Kazzz-S** [comment]
cont.

The above application bundle built on `Monterey` can also run on `Ventura` and `Sonoma`. 
![Ventura](https://github.com/KLayout/klayout/assets/16847255/e9bf3700-864f-4d42-b7e0-13da72e45c6f)

![Sonoma](https://github.com/KLayout/klayout/assets/16847255/0c69705b-67a4-42aa-9795-5b29e336d739)

Kazzz-S

**Comment by Kazzz-S** [comment]
## 2. Linux Mint 21.3 ##

Using the same source code as macOS...
![Mint-213-A](https://github.com/KLayout/klayout/assets/16847255/11914195-6fc6-4fa4-9a84-3623823bb666)
![Mint-213-B](https://github.com/KLayout/klayout/assets/16847255/f78ec473-0671-4436-a86b-cff77af8373c)

Kazzz-S

**Comment by stefanottili** [comment]
Works on M1 macOS Sonoma too.

**Comment by klayoutmatthias** [comment]
Very good. Thanks for the patch (interesting, how different the GLSL implementations are) and the feedback!

I am happy to hear it works on MacOS too - OpenGL really is weird. 

I will include the new version in the next 0.29.1 release (tomorrow, hopefully). From the memory perspective, I conducted an experiment with about 20M shapes (boxes). During 2.5d rendering with some booleans and mesh lines, memory goes up to 14G, but I hope that is an extreme case. As I was removing the geometry renderer, I now need to supply normal vectors for the lighting and this doubles the vertex memory. It is possible to reduce the footprint by using indexed buffers, but I first need to learn how to use them properly. I spare that for a future release :)

Best regards and thanks again,

Matthias

**Comment by klayoutmatthias** [comment]
My 20M rectangle test case (sluggish ...)

![image](https://github.com/KLayout/klayout/assets/25720841/146a487d-f41d-46a0-a8ae-50c33bdc9065)

**Comment by ejprinz** [comment]
Tested on RedHat EL8. Works fine.

**Comment by klayoutmatthias** [comment]
Closing, as it is released. Thanks for your support!
