### ISSUE TITLE
[macOS] User Properties Dialog Crashes

### ISSUE THREAD

**Issue by Kazzz-S** [KLayout/klayout#1706]
## 1. The Latest Version (0.29.1) ##

The `User Properties` dialog crashes when I click the `[User Properties]` button.
This problem reproduces with the latest four binaries listed below.
![0291DMGs](https://github.com/KLayout/klayout/assets/16847255/c72a6180-2d7b-4b18-a93f-701e64ef9763)
[02901-crash-logs.zip](https://github.com/KLayout/klayout/files/15268710/02901-crash-logs.zip)

I used this feature before. I recently started using it again after a long hiatus and noticed this problem.

This problem is macOS-specific.
This feature works as expected in the Linux and Windows environments, as shown in the images below.
![OK-Linux-Mint21 3](https://github.com/KLayout/klayout/assets/16847255/51f2c704-c0c8-4913-8ad7-4751585e8c57)
![OK-Windows10](https://github.com/KLayout/klayout/assets/16847255/88da48e0-833b-428e-b2c8-380c9ec62190)

To be continued...

**Comment by Kazzz-S** [comment]
Cont.

## 2. Previous Versions (< 0.29.1) ##

I tested previous versions with HW*.dmg going back in history.
Then, I found versions up to 0.28.8 are problematic.
```
<0.29.1> --> 0.28.17 --> 0.28.15 --> 0.28.14 --> 0.28.13 --> 0.28.12 --> 0.28.11 --> 0.28.10 --> 0.28.9 --> 0.28.8
```
[previous-crash-logs.zip](https://github.com/KLayout/klayout/files/15268879/previous-crash-logs.zip)

To be continued...

**Comment by Kazzz-S** [comment]
Cont.

## 3. Further Previous Versions (< 0.28.8) ##
I tested with `0.28.7`, `0.27.13`, and `0.26.12` and found they are OK, as shown in the sample images below.
![02807HW-a](https://github.com/KLayout/klayout/assets/16847255/f45025a5-aa18-4478-95b2-ae4b62c6d007)
![02807HW-b](https://github.com/KLayout/klayout/assets/16847255/c3b8b56a-0f75-4637-b29f-34d6a4959994)
[OK-samples.zip](https://github.com/KLayout/klayout/files/15268945/OK-samples.zip)

I suspect some problem may have intruded between `0.28.7` and `0.28.8`.

Best regards,
Kazzz-S

**Comment by klayoutmatthias** [comment]
Thanks for the analysis. I will look into that.

Matthias

**Comment by Kazzz-S** [comment]
Cont.

## 4. With Qt6 ##

It works with Qt6!

![02901-ST-Qt6](https://github.com/KLayout/klayout/assets/16847255/84c61bf2-bd04-48be-b084-1551d7fd3376)
----
![02910-HWports-Qt6](https://github.com/KLayout/klayout/assets/16847255/7e9d0bfe-187b-4053-b31c-cf240742dc9d)

**Comment by Kazzz-S** [comment]
Cont.

## 5. Qt-wise Status ##
![Qts](https://github.com/KLayout/klayout/assets/16847255/07fe1db2-d69a-4d2e-bb49-8c13bd315d09)

[Qts.xlsx](https://github.com/KLayout/klayout/files/15281954/Qts.xlsx)

Thanks,
Kazzz-S

**Comment by stefanottili** [comment]
on M1 lastest master:
homebrew qt 5.15.13 coredump
homebrew qt 6.7 works

**Comment by klayoutmatthias** [comment]
Dear @Kazzz-S  and @stefanottili

Thanks for the many datapoints and your experiments!

Maybe I found the root cause: on some platforms / compilers, a default-initialized iterator appears no to have the same value.

My patch is here: https://github.com/KLayout/klayout/pull/1708

Maybe you can try whether this fixes the problem.

Thanks and best regards,

Matthias

**Comment by klayoutmatthias** [comment]
P.S: I hope you did not spend too much effort in your research. Basically all I needed was the hint about 0.28.7 vs. 0.28.8 :(

**Comment by stefanottili** [comment]
git checkout origin/bugfix/issue-1706 fixes the coredump on M1 Sonoma.

The fact that it went unreported for so many versions just might indicate that nobody is using this feature ...

**Comment by Kazzz-S** [comment]
Hello @klayoutmatthias,

Thank you for trying to fix this problem.
Using the patch #1708, I rebuilt:
1. Four binaries with Qt5.x mentioned in [this table](https://github.com/KLayout/klayout/issues/1706#issue-2288649465).
2. Two binaries with Qt6.x mentioned in [this comment](https://github.com/KLayout/klayout/issues/1706#issuecomment-2105605659).
3. One binary with Qt5.12.8 on Linux Mint 20.3.

I confirmed that all 7 test cases are OK.

Thank you again, and best regards,
Kazzz-S

**Comment by Kazzz-S** [comment]
Hello @stefanottili,

Thank you for testing on M1 Sonoma.
I use this feature mainly in Linux environments, so I overlooked this problem till recently.

Best regards,
Kazzz-S
