### ISSUE TITLE
sky130A pymacros & gdsfactory

### ISSUE THREAD

**Issue by martinjankoehler** [KLayout/klayout#1731]
Hi @klayoutmatthias,

encounterd some issues trying to enable sky130A pymacros in edit mode
(perhaps not really klayout but rather PDK authors / gdsfactory issues),
but perhaps somebody knows a workaround

## XML parsing issue

The pymacros do not work, due to comment before the XML declaration:
`/foss/pdks/sky130A/libs.tech/klayout/pymacros/sky130.lym`
I guess this issue should really be fixed by the PDK authors, but perhaps klayout could gracefully handle this.

![Bildschirmfoto 2024-06-06 um 16 14 05](https://github.com/KLayout/klayout/assets/29398377/39d418ca-d6cc-45c2-864a-eb98fcd2482c)

After fixing this manually by moving up the XML declaration to the top, then I get...

## gdsfactory issue

![Bildschirmfoto 2024-06-06 um 16 05 10](https://github.com/KLayout/klayout/assets/29398377/e8e5c3d2-e1c3-48b6-912c-7d3e2ff5a97e)

Are these known issues?

I have those with:
- Docker: hpretl/iic-osic-tools:2024.05
- Docker: hpretl/iic-osic-tools:2024.04 
- MacOS 10.14

Will try to install an older PIP version of gdsfactory.

**Comment by martinjankoehler** [comment]
OK, seems with `gdsfactory 6.34.0` they moved `gdsfactory.types` to `gdsfactory.typings`: https://gdsfactory.github.io/gdsfactory/changelog.html#id193

So replacing all the `import` statements gets it to work.

**Comment by klayoutmatthias** [comment]
Hi Martin,

I am not sure if I can skip the comment - that is eventually Qt's XML parser. Optional I can use expat, but if the XML is not well-formed, this one would error out is well, I assume.

Matthias

**Comment by klayoutmatthias** [comment]
I found this commit: https://github.com/efabless/sky130_klayout_pdk/commit/c49c741c09bf0cb31b9af76aa53f4b9502e0d17a

So apparently the authors are aware of this problem :)

**Comment by martinjankoehler** [comment]
Thanks, I‘ll close this issue.

**Comment by martinjankoehler** [comment]
FYI, I've opened an issue there for the import error: https://github.com/efabless/sky130_klayout_pdk/issues/20
and also have a fix handy: https://github.com/martinjankoehler/sky130_klayout_pdk/tree/gdsfactory-types-fix
