### ISSUE TITLE
Instance selecion in object properties does not match with view port object highlight

### ISSUE THREAD

**Issue by s910324** [KLayout/klayout#1733]
System : Windows 11 x64
Software : Klayout 0.29.1 portable

Hi recently  I have encounter a senerio that the selection of instance does not correlate well with the selection indicatiob in view port
following video shows a grouped selection of  4 instance + one rectangular, when I switch to choose `TEXT` instance, the view port hightlights the `FiducialMark` instance instead.

It seems only affects view port hight light, and does not affect the info displayed on property window.

https://github.com/KLayout/klayout/assets/1561043/db9e9a44-5e0b-4a6d-9183-4fd0b04b7ebf

It occurs randomly so i think it might provide some hint with the layout attached.
[Selection_test.zip](https://github.com/user-attachments/files/15710036/Selection_test.zip)

Thank you.

**Comment by klayoutmatthias** [comment]
Thanks a lot for the test case. The issue reproduces for me. 

I will take a look and try to fix it on the next minor release.

Best regards,

Matthias
