### ISSUE TITLE
Made DXF file on autoCAD - will not open on KLayout

### ISSUE THREAD

**Issue by cw162** [KLayout/klayout#1748]
Hello, 
I have a drawing I made in AutoCAD for a photomask in microns, attached here as drawing2 in the zipfile. 
[Drawing2.zip](https://github.com/user-attachments/files/15905354/Drawing2.zip)

It looks like this 
<img width="674" alt="image" src="https://github.com/KLayout/klayout/assets/173305188/417364b4-43a0-4b60-a7b9-db76839ba88d">

I need to open it in KLayout as that is the software in the cleanroom. However, I kept getting the "Coordinate value overflow" error. 

I've tried to play around with the file/reader options for opening the DXF and the only database unit that works is setting to 1 um
<img width="455" alt="image" src="https://github.com/KLayout/klayout/assets/173305188/f2027506-7976-4e92-a0a2-ed80666568cc">
but once it does get it open, it just looks like a giant purple circle and not my pattern, 

<img width="611" alt="image" src="https://github.com/KLayout/klayout/assets/173305188/4f75117a-df64-4e64-836d-c697e5da3200">

Can anyone please help? I just want to open my file on Klayout

**Comment by Kazzz-S** [comment]
### 1. Introduction ###

**My Work Environment**
1. OS: Linux Mint 20.3
2. KLayout: 0.29.2 (source build)
3. CAD for DXF: QCAD Professional 3.30.1

**Observations**
1. At a glance, the DXF file size (300MB) looks too huge compared with the complexity of the shapes drawn.
2. I could reproduce the problems described above.
3. The diameter of the giant purple circle is `140 meters`!
4. I copied and saved a part of the design (ex. `AREA 00`) to another DXF, whose size is only 253KB.
5. Therefore, the DXF file must contain plenty of invisible (and harmful for KLayout) data.

To be continued.

**Comment by Kazzz-S** [comment]
Cont.

### 2. Generating Leaner DXFs ###

* I selected ALL items and copied them to an empty sheet to generate `Drawing2A.dxf`.
* The file size is reduced to 1/100 of the original size.
* I manually edited (described later) `Drawing2A.dxf` to generate `Drawing2B.dxf`.
![FileSize](https://github.com/KLayout/klayout/assets/16847255/82a7e14c-055e-4baf-ac39-ac6c38ee04ba)

To be continued.

**Comment by Kazzz-S** [comment]
Cont.

### 3. Drawing2A.dxf and Option-[1|2] ###
![Op1](https://github.com/KLayout/klayout/assets/16847255/b10d0e86-4396-49e1-a1eb-8089479bfc2d)
* With above Option-1, DXF ---> OASIS conversion was successful.
* However, one rectangle is missing, as shown below.
![Drawing2A-op1 oas](https://github.com/KLayout/klayout/assets/16847255/47e69e1f-e3e3-4d45-8443-3b38e790b46a)

----

![Op2](https://github.com/KLayout/klayout/assets/16847255/391755bd-1a3d-4a5d-9ce8-7bcd43543a61)
* With above Option-2, DXF ---> OASIS conversion was also successful.
* The rectangle appears, but is it OK?
![Drawing2A-op2-a oas](https://github.com/KLayout/klayout/assets/16847255/43645a83-b789-4e30-81f8-6e2d1bc0832d)
![Drawing2A-op2-b oas](https://github.com/KLayout/klayout/assets/16847255/5eafec2f-d524-4f24-a807-eb10a87c9fbf)

* The rectangle consists of `1 closed poly-line` and `4 individual lines`.
* The latter are connected to a single closed poly-line while reading.
* Then, when converting to polygons (with inside-outside discrimination), 2 overlapping poly-lines cancel each other and disappear.

To be continued.

**Comment by Kazzz-S** [comment]
Cont.

### 4. Drawing2B.dxf and Option-1 ###
![Op1](https://github.com/KLayout/klayout/assets/16847255/ddb3e30c-b922-4d6a-ba93-889b9768fba4)
* I deleted the `4 individual lines` to generate `Drawing2B.dxf`.
* With above Option-1, DXF ---> OASIS conversion was successful.
* The output is now OK, as shown below.
![Drawing2B-op1 oas](https://github.com/KLayout/klayout/assets/16847255/9207d45c-46b3-4230-83b7-c8c62d27aa7a)

**Comment by Kazzz-S** [comment]
Cont.

### 5. Summary ###
1. I suggest first cleaning up the original design in DXF.
2. Switching the reader options (as seen above) would help to detect potential errors.
3. All relevant files ===>  [GitHub1748.zip](https://github.com/user-attachments/files/15908793/GitHub1748.zip)

Regards,
Kazzz-S

**Comment by cw162** [comment]
Thank you very much for looking into the problem and troubleshooting! The problem was a lot more complex that I would have thought. Ill likely stick to Klayout for now as you suggest
