### ISSUE TITLE
RecursiveInstanceIterator cell_index

### ISSUE THREAD

**Issue by frankxu-omni** [KLayout/klayout#1749]
I have nested.oas looks like this.
![hiearchy](https://github.com/KLayout/klayout/assets/137927478/5f335813-c615-443f-bedc-7a6f27a1e5d3)

code:
![code](https://github.com/KLayout/klayout/assets/137927478/28fa145b-304a-4dd0-a475-a64d39f808d8)

ouput:
![output](https://github.com/KLayout/klayout/assets/137927478/fc514ea9-f9b8-4ed7-a8de-8f8af10905f3)

I wonder why cell indexes are not matched. 

I attached test case below.
[iter_cell_index.zip](https://github.com/user-attachments/files/15917893/iter_cell_index.zip)

**Comment by Kazzz-S** [comment]
My understanding is as follows.
I've slightly modified the code.

![gh1749-slide-1](https://github.com/KLayout/klayout/assets/16847255/75c66089-1f40-41e6-9d20-f73f7060422d)
![gh1749-slide-2](https://github.com/KLayout/klayout/assets/16847255/f8fdcbd7-bb5d-4cc3-92af-ad1e67aeeff4)
![gh1749-slide-3](https://github.com/KLayout/klayout/assets/16847255/c5bd6e72-29bf-46bc-9706-0a9cb2a07771)

* PPT ===> [gh1749-KazzzS.zip](https://github.com/user-attachments/files/15921870/gh1749-KazzzS.zip)

**Comment by frankxu-omni** [comment]
Hi Kazunari,
Your explanation is clear.  I see now. I was confused by "current instance sits in".  That really means its parent cell. 
Good graphical demo. I like that. 
Thanks, 
-Frank
