### ISSUE TITLE
Tools --> Manage Packages Timeout

### ISSUE THREAD

**Issue by Kazzz-S** [KLayout/klayout#1756]
The original issue: https://www.klayout.de/forum/discussion/2525/

The `Tools --> Manage Packages` operation often failed with a timeout (10s) in a particular Internet environment.
More details follow after [this link](https://www.klayout.de/forum/discussion/comment/10982/#Comment_10982).

**Comment by Kazzz-S** [comment]
Enhance by #1764

**Comment by Kazzz-S** [comment]
This enhancement seems missing in the ChangeLog for 0.29.3 2c0a7f79

**Comment by klayoutmatthias** [comment]
No, I wrote the changelog too early :)

I will add it. Thanks for the hint!

Matthias
