### ISSUE TITLE
layer_into (typo for layer_info?) in doc/about/drc_ref_source.html

### ISSUE THREAD

**Issue by sto6** [KLayout/klayout#1769]
On https://www.klayout.de/doc/about/drc_ref_source.html
page as	a whole, enumerates argument signatures using "layer_into" several times like:

`source.input(layer_into)`

Text does not mention/explain _layer_into_ but mentions `LayerInfo` as in:

> ... The layer can be specified by layer and optionally datatype, by a LayerInfo object or ...

Are those _layer_into_ typos for _layer_info_ (else what does it mean)?

**Comment by klayoutmatthias** [comment]
Thanks. That is a type of course. It is meant to be "layer_info" and it means "a `LayerInfo` object".

Matthias
