### ISSUE TITLE
Macro development step over/into does not work in some cases

### ISSUE THREAD

**Issue by Kazzz-S** [KLayout/klayout#1770]
Hello @klayoutmatthias,

The green arrow (**=>**) stops at a breakpoint in the macro development tool.
But it would not move with the step over/into button clicks in some builds.
![Macro-StepOver](https://github.com/KLayout/klayout/assets/16847255/ec71aa16-7eab-497a-b828-0ca76026ca1f)

I have found 3 out of 17 cases, as shown in the table below. [StepOver-Problem.xlsx](https://github.com/user-attachments/files/16093089/StepOver-Problem.xlsx)
![StepOver-Problem](https://github.com/KLayout/klayout/assets/16847255/b177d222-ea90-40b8-88d9-c406392742fa)

I found this problem yesterday (first in Srl. No.10), but I need help determining the possible cause.
Do you have any suggestions, like increasing the verbosity level?

Best regards,
Kazzz-S

**Comment by klayoutmatthias** [comment]
Hi @Kazzz-S,

thanks for reporting this. It reproduces very well.

I had this issue when modal dialog were opened during debugging, but apparently that applies always. I should not have deleted line 3767 in https://github.com/KLayout/klayout/commit/0a453b069c58f8dbf382adfa14ae7f97caab0966 :(

There is no trace one can easily turn on. The way to debug this is in C++, setting a breakpoint in this function:

![image](https://github.com/KLayout/klayout/assets/25720841/891bbb41-de6c-47a4-8993-b131f1e928ed)

The marked loop does not exit, as the "m_in_breakpoint" flag is not reset.

Matthias

**Comment by Kazzz-S** [comment]
Hi @klayoutmatthias,

Thanks for the quick fix :-)
Now `Srl. No.10` works fine. 
I'll test the other two later at home.

Kazzz-S

**Comment by Kazzz-S** [comment]
Cont.

I have also confirmed that `Srl. No.1` and `No.8` work fine.

Thanks
Kazzz-S

**Comment by klayoutmatthias** [comment]
Very good - thanks for letting me know and thank you for this report! :)

Best regards,

Matthias
