### ISSUE TITLE
Klayout document PDF didn't update for 2 versions

### ISSUE THREAD

**Issue by dsus4wang** [KLayout/klayout#1773]
Hi, I found the version of klayout document (PDF) is still for 0.29.0, but the current klayout version is 0.29.2.
Is that a automatic update issue?
Thanks.

**Comment by klayoutmatthias** [comment]
Yes, you're right. There was a problem with the upload script. I will fix that on the next release. Which is now :)

Thanks for reporting this problem.

Matthias

**Comment by klayoutmatthias** [comment]
Thanks for reporting the problem. Scripts are fixed and PDF is up to date (0.29.3).

Matthias

**Comment by dsus4wang** [comment]
Thanks a lot!
