### ISSUE TITLE
klayout_pyxs macro dissappeard in tool menu after klayout update to 0.29 version.

### ISSUE THREAD

**Issue by ernie14674560** [KLayout/klayout#1826]
As indicated in the title, after updating klayout 0.29 from 0.28.17, pyxs macro disappears in the tool menu. I have to downgrade to 0.28.17 to make it back. Any help?

**Comment by klayoutmatthias** [comment]
This project appears to be out of maintenance and I am not the author.

**Comment by ernie14674560** [comment]
OK! thanks for the info. I fix the problem myself by editing the klayou_pyxs python code. Apparently, there are some pya features that have been updated in version 0.29 causing this macro to fail to execute.

**Comment by klayoutmatthias** [comment]
Very good :)

I think the pyxs people would love to have your patches. Do you consider filing a PR on their project?

Matthias
