### ISSUE TITLE
Windows wheels missing for 0.29.6

### ISSUE THREAD

**Issue by sebastian-goeldi** [KLayout/klayout#1830]
Hello Matthias,

Just to let you know. The wheels for windows seem to not have been uploaded to pypi for 0.29.6.

I hope it's an easy fix. If not lmk and I am happy to go investigate as well.

Best,
Sebastian

**Comment by klayoutmatthias** [comment]
Somehow the Azure pipeline did not trigger upon release. I have restarted the pipeline with the release tag. Let's see if that solves the issue.

Matthias

**Comment by sebastian-goeldi** [comment]
yep, they are there there now, thanks Matthias!

![image](https://github.com/user-attachments/assets/6b6d1c2d-0299-4685-a730-d19c8b6983ec)
