### ISSUE TITLE
is it possible to control the visible grid?

### ISSUE THREAD

**Issue by olisnr** [KLayout/klayout#1833]
in the `Editor Options` i can set a snap-grid. 

but i have no idea where to set the shown grid. per default it change in function of the zoom, but some times i would like to set it to a different spacing my self (160nm as example). is it possible to do this?

**Comment by klayoutmatthias** [comment]
You can set the grid in "File/Setup", "Application/Grid" and "Application/Default Grid" pages.

But basically this is issue tracker here and I'd appreciate if you use it for issues, not support questions. Issues get closed eventually and there is no further value of this answer for others. There is a forum for user questions: https://www.klayout.de/forum/. If you apply, please be a little patient as accounts get approved after review. Two thirds of the applications are spammers.

Matthias

**Comment by olisnr** [comment]
thanks
