### ISSUE TITLE
little problem with File::Setup/Application::Customize Menu

### ISSUE THREAD

**Issue by olisnr** [KLayout/klayout#1847]
if i use KLayout from a new `KLAYOUT_HOME` path, the dialog `File::Setup/Application::Customize Menu` is the 1st time uninitialized: the shortcut-row is empty. it stays even empty after `Reset To Default` but shows up after clicking `Apply`.

may be, there is some initialization order wrong?

**Comment by klayoutmatthias** [comment]
There is something wrong, right.

I will take a look into that.

Matthias

**Comment by olisnr** [comment]
very fast fixed! thanks a lot
