### ISSUE TITLE
strange menues in LiNUX MiNT on HiDPi

### ISSUE THREAD

**Issue by olisnr** [KLayout/klayout#1852]
on a 4k notbook, where the display is scaled 200%, the menues of KLayout has unnatural space between the lines. 

![Screenshot 2024-09-08 01:05:58](https://github.com/user-attachments/assets/f7763d69-2a4f-4e9e-a3c1-0ea935ec8452)

as reference xed:

![xed](https://github.com/user-attachments/assets/4ece2272-c00f-43d0-8df7-23ca545a51e7)

at 100% there is no difference.

**Comment by klayoutmatthias** [comment]
I'm sorry, but that is a Qt/GTK or whatever other issue I am not going to debug. I am using a 4k screen on a Notebook myself without issues on Ubuntu 24.

**Comment by olisnr** [comment]
can You tell me Your window manager? then may be i find the whatever faster :)
