### ISSUE TITLE
A bug about layer undo

### ISSUE THREAD

**Issue by puslim** [KLayout/klayout#1860]
1. create a layer
2. create a box on the layer
3. delete the layer
4. press undo
5. create new layer
After those steps , I found the box is changing into the new layer
I thought there is something wrong of dbLayoutLayers.cc:263(LayoutLayers::do_insert_layer).
Maybe m_free_indices should find the index and remove it.

**Comment by klayoutmatthias** [comment]
You were right with your analysis. Good catch. The bug must be have been there forever. I wonder how come no one noticed ...

Thanks,

Matthias
