### ISSUE TITLE
strmxor test.oas empty.oas xor.oas should use test.oas top cellname, not XOR

### ISSUE THREAD

**Issue by stefanottili** [KLayout/klayout#1869]
```
strmxor -l test.oas empty.oas xor.oas
klayout test.oas -s empty.oas -m xor.oas
```
loads the xor result file.
Trying to navigate to the errors in the Marker Database Browser shows:
```
0/0 [XOR]
Current layout cell 'test' not found in marker database and no path found from marker's cell 'XOR' to current cell in the layout database.
```
Instead of XOR strmxor should use the toplevel cellname of the first layout file.
[test.tgz](https://github.com/user-attachments/files/17106380/test.tgz)

**Comment by klayoutmatthias** [comment]
By default, strmxor will not use the top cell of the first layout. If you want to have "XOR" back, there is a specific option for the output top cell now: `-to <output-cell>` or `--top-output <output-cell>"
