### ISSUE TITLE
Add `(D)Point.move(d)`

### ISSUE THREAD

**Issue by sebastian-goeldi** [KLayout/klayout#1923]
Hi Matthias,

I noticed basically all shape-like objects except the point ones have a `move(d)` function. Would it be possible to add this for Point as well?

Also, one additional question, but maybe that's not possible due to footprint matching. Would it be possible to add 0 as a default value for `dx`/`dy`? Rational being then (in python at least), you can do `point.move(dy=500)` without needing to specify `dx` and the other way around. This would be purely convenience, so if not easily achievable, that's totally okay!

**Comment by klayoutmatthias** [comment]
I also harmonized the parameter names ("dx", "dy") and added the default "0" for dx/dy to other objects such as edges, polygons, regions etc.

I hope this does not break anything.
