### ISSUE TITLE
MAGIC import fails

### ISSUE THREAD

**Issue by martinjankoehler** [KLayout/klayout#1925]
![image](https://github.com/user-attachments/assets/9bb1cecf-8224-482a-b2be-e7ba7dc7ba10)

The cursor here shows the line 337:
![Bildschirmfoto 2024-11-15 um 17 12 45](https://github.com/user-attachments/assets/b0ddfd43-28de-4e86-9e93-f5ad95731522)

Reduced:
[redux.mag.zip](https://github.com/user-attachments/files/17778185/redux.mag.zip)

Seems the `s` is optional, if I remove it the import works:
[redux-workaround.mag.zip](https://github.com/user-attachments/files/17778202/redux-workaround.mag.zip)

**Comment by klayoutmatthias** [comment]
I found the reader code in Magic. "s" is optional and goes into some "stickyflag" 1-character string. But I do not see anything done with it, so I assume it's a legacy thing.

I will ignore the "s" for now.

Matthias
