### ISSUE TITLE
Selection of structures results in thick black lines

### ISSUE THREAD

**Issue by hpretl** [KLayout/klayout#1930]
When I use KLayout 0.29.8 inside a Docker VM based on Ubuntu 22.04LTS, and when I am on a **Arm-based Mac** (_not happening on Intel-based Macs_) then I get a thick black selection frame when clicking on a layout structure:

![image](https://github.com/user-attachments/assets/a6c13b76-76a2-4b10-842c-b35ec00c902b)

Interestingly, when I hover the mouse over a structure, there is also a black line indicating a to-be selected layout structure, but this black “frame” looks OK:

![image](https://github.com/user-attachments/assets/fd6943ff-b4c5-46bc-b05c-15a8bc5b8ca6)

@klayoutmatthias Any idea what is going on? The problem is that this thick black border on selected items is really annoying, as it overlays other things that would be necessary to see. All other graphical elements in KLayout look fine, just this selection border is too wide.

As a side note, turning off “with halo” or playing around with line width in the Setup Selection does not help.

**Comment by martinjankoehler** [comment]
FYI, I can also reproduce it using VNC (instead of X11):
![Bildschirmfoto 2024-11-18 um 20 20 11](https://github.com/user-attachments/assets/d56b497c-d512-49c6-a9fd-1882f9e61692)

**Comment by martinjankoehler** [comment]
Compiler warning hints at the reason:
```
../../../src/laybasic/laybasic/layMarker.cc: In member function \u2018void lay::MarkerBase::get_bitmaps(const lay::Viewport&, lay::ViewObjectCanvas&, lay::CanvasPlane*&, lay::CanvasPlane*&, lay::CanvasPlane*&, lay::CanvasPlane*&)\u2019:
../../../src/laybasic/laybasic/layMarker.cc:326:33: warning: comparison is always false due to limited range of data type [-Wtype-limits]
  326 |   int line_width = m_line_width < 0 ? mp_view->default_marker_line_width () : m_line_width;
      |                    ~~~~~~~~~~~~~^~~
../../../src/laybasic/laybasic/layMarker.cc:327:35: warning: comparison is always false due to limited range of data type [-Wtype-limits]
  327 |   int vertex_size = m_vertex_size < 0 ? mp_view->default_marker_vertex_size () : m_vertex_size;
      |                     ~~~~~~~~~~~~~~^~~
../../../src/laybasic/laybasic/layMarker.cc:328:22: warning: comparison is always false due to limited range of data type [-Wtype-limits]
  328 |   bool halo = m_halo < 0 ? mp_view->default_marker_halo () : (m_halo != 0);
      |               ~~~~~~~^~~
```

**Comment by klayoutmatthias** [comment]
Some problems like the signed vs. unsigned char never get resolved ... I usually avoid using char for integers, but this case escaped me. All my gccs, clangs and MSVCs treat it as signed on Windows and Linux. 

I even get this warning from clang:

```
c.x:14:
char c;
c = 128;

gives:
x.c:14:7: warning: implicit conversion from 'int' to 'char' changes value from 128 to -128 [-Wconstant-conversion]
```

which is rather suggesting that char is signed.

Anyway, problem is fixed. Thanks for the PR.

Matthias

**Comment by hpretl** [comment]
Thanks, fixed, closing issues.
