### ISSUE TITLE
Version 0.29.9 crash

### ISSUE THREAD

**Issue by Kazzz-S** [KLayout/klayout#1941]
Hello @klayoutmatthias,

Thank you for making the maintenance release of 0.29.9.
Unfortunately, I'm facing a crash when opening a simple design. [gds.zip](https://github.com/user-attachments/files/17971564/gds.zip)

----

![KL0299-Win11](https://github.com/user-attachments/assets/237250fa-cc15-43e3-9187-282ab9cf4f6a)
![KL0299-Mint203](https://github.com/user-attachments/assets/0dcbd56d-158c-4a65-a44a-02cfcb154e2e)
* Ubuntu 20 binary package **klayout_0.29.9-1_amd64.deb (64bit)** also crashes in the same environment.
* **klayout_0.29.8-1_amd64.deb (64bit)** is OK.

----

**Valgrind on Linux Mint 20.3**
![KL0299-Mint203-Valgrind](https://github.com/user-attachments/assets/1f5d333a-c8cc-4dbe-9b20-26c460ebe9a6)
[KL0299-Mint203-Valgrind.zip](https://github.com/user-attachments/files/17971563/KL0299-Mint203-Valgrind.zip)

----

I also built the five DMGs as usual and found all crashed.
![KL0299-Sonoma](https://github.com/user-attachments/assets/7c7658d4-7ac3-4243-ac1b-5a3a5386bb1e)

Best regards,
Kazzz-S

**Comment by klayoutmatthias** [comment]
Hi Kazzz-S.You are right. I have no idea why the released version does that. I was working nicely for my builds.I will check what is wrong. I think I will create a hot fix for that problem.MatthiasSent from Android deviceOn Dec 2, 2024 03:02, Kazunari Sekigawa ***@***.***> wrote:
Hello @klayoutmatthias,
Thank you for making the maintenance release of 0.29.9.
Unfortunately, I'm facing a crash when opening a simple design. gds.zip

KL0299-Win11.png (view on web)
KL0299-Mint203.png (view on web)

Valgrind on Linux
KL0299-Mint203-Valgrind.png (view on web)
KL0299-Mint203-Valgrind.zip

I'm also currently building it on my Mac. I could add more information tonight.
Best regards,
Kazzz-S

**Comment by Kazzz-S** [comment]
Yes!

![KL0299-Sonoma-NoNavigator](https://github.com/user-attachments/assets/0323431b-07be-44de-addd-6a96cdf1aaeb)

Kazzz-S

**Comment by klayoutmatthias** [comment]
I have fixed the problem. 

As 0.29.9 is not quite useful with the bug, it makes sense to wait for 0.29.10 before creating the DMGs.

Sorry the for inconvenience. It's very busy right now. Too little time for testing :(

Matthias

**Comment by Kazzz-S** [comment]
![KL02910-Sonoma-WithNavigator](https://github.com/user-attachments/assets/02042f22-f325-4853-8e3f-584e047df10c)

Kazzz-S

**Comment by klayoutmatthias** [comment]
Thanks a lot for testing!

I just released 0.29.10. I hope this is a good one then :)

Best regards,

Matthias
