### ISSUE TITLE
Oasis write fails for big arrays (>32767 columns/rows) if `LayoutSaveOptions` is passed

### ISSUE THREAD

**Issue by sebastian-goeldi** [KLayout/klayout#1952]
Context:

In kfactory I am setting a bunch of default write options (this is in order more standard fab requirements and to decrease unintentional foot shooting).

Bug:

It seems if some of the `gds2_[...]` in the `options` of `db.Cell.write` (I suspect `db.Layout.write` too), the oasis writer still calls at least some checks or functions from the gds2-streamer. And the streamer fails for big arrays (the int16 limit there I think).

Code to reproduce:

```python

import klayout.db as db

ly = db.Layout()
f_cell = ly.create_cell("F")
l1 = ly.layer(1, 0)

path_cell = ly.create_cell("P")
pts = [db.DPoint(0, 0), db.DPoint(1, 0)]
point = db.DPath(pts=pts, width=0.5)
path_cell.shapes(l1).insert(point)

top_cell = ly.create_cell("TOP")

i1 = db.DCellInstArray(
    cell_index=path_cell.cell_index(),
    trans=db.DTrans(1, False, 10.0, 5.0),
    a=db.DVector(0, 2),
    b=db.DVector(2, 0),
    na=32768,
    nb=32768,
)
top_cell.insert(i1)

saveopts = db.SaveLayoutOptions()

# ly.write("kl_big_array.oas")  # works
ly.write("kl_big_array.oas", options=saveopts)  # fails because int16 restriction
```

If the `options=` is omitted, it works.

This was discovered in https://github.com/gdsfactory/gdsfactory/discussions/3476

**Comment by klayoutmatthias** [comment]
That is an easy one :)

Problem is that `SaveLayoutOptions` also indicates the file format. 

This is one important note from the documentation: 

```
Usually the default constructor provides a suitable object. Please note, that the format written is "GDS2" by default. Either explicitly set a format using "format=" or derive the format from the file name using "set_format_from_filename".
```

That has been a backward compatibility feature and it is a good idea to keep format and streaming functions separate, for example to implement the recent "write_bytes" extension.

In your case this code will fix your problem:

```
...
fn = "kl_big_array.oas"

saveopts = db.SaveLayoutOptions()
saveopts.set_format_from_filename(fn)

ly.write(fn, options=saveopts)
```

The version without options does the same thing internally.

Matthias

**Comment by sebastian-goeldi** [comment]
Ah, I see. Well, then that's definitely on me :smile:

**Comment by sebastian-goeldi** [comment]
Would it be possible to get klayout to emit a warning in case the `SaveLayoutOptions` file suffix doesn't match the written one?
