### ISSUE TITLE
 error in XOR operation in Boolean operation

### ISSUE THREAD

**Issue by t0mhuang** [KLayout/klayout#1957]
Two Regions in the C++DB library in klayout29.6 are carried out, and the XOR operation in the Boolean operation is wrong, and the result obtained is the result after merge。The problem is in the bool_xor and operation^ functions in db::Region。I went to check your source code and got the correct result by the following way, I hope you can modify the external interface function bool_xor and operator^ function interface you provided.

```
void KalyoutBool(db::Region& rg1,db::Region& rg2,db::Region& re_rg,db::BooleanOp bOp){
    db::EdgeProcessor ep;
    for (db::RegionIterator iterPly = rg1.begin (); !iterPly.at_end(); ++iterPly){
        ep.insert (*iterPly, 0);
    }

    for (db::RegionIterator iterPly = rg2.begin (); !iterPly.at_end(); ++iterPly) {
        ep.insert (*iterPly, 1);
    }

    std::vector<db::Polygon> out;
    db::PolygonContainer pc (out);
    db::PolygonGenerator pg (pc, false, true);
    db::BooleanOp op (bOp);
    ep.process (pg,  op);
    for(int ii = 0; ii < out.size(); ++ii) {
        re_rg.insert(out[ii]);
    }
}
```

**Comment by klayoutmatthias** [comment]
I am sorry, I don't understand a single word.

What is that? Is that a bug report? This is basically the code that happens internally in ` dbAsIfFlatRegion.cc:1746++`.

Is this an AI generated issue? 

Matthias
