### ISSUE TITLE
[bug] Python Script for plotting rounded path

### ISSUE THREAD

**Issue by luomeng007** [KLayout/klayout#1961]
When I use code to draw a path Cell like below I got correct result. 
```
obj = pya.Path(points, width, bgn_ext, end_ext, r)
print(obj) # (0,0;1,0;1,1;2,1) w=1 bx=1 ex=1 r=true
```
But when I write this path into .gds file,  the end facet of path is not round,  is this a bug or somthing? The figure in .gds file is like below:

![image](https://github.com/user-attachments/assets/a977e380-ebe7-4e4e-8307-5967aeaf1ed9)

**Comment by luomeng007** [comment]
I have already get answer from forum side. Thanks guys.

**Comment by sebastian-goeldi** [comment]
@luomeng007 could you maybe link the post here, just for completeness sake? ;)

To avoid this: https://xkcd.com/979/ :D

**Comment by luomeng007** [comment]
Fine, here it is. [The anwser](https://www.klayout.de/forum/discussion/2644/can-not-get-rounded-end-by-using-pya-path-command#latest)
