### ISSUE TITLE
Crash with custom stipple pattern that contain more than 38 lines

### ISSUE THREAD

**Issue by klayoutmatthias** [KLayout/klayout#232]
Klayout reads 38 lines but not more than that … 

Test case to be added.

**Comment by klayoutmatthias** [comment]
Here is a testcase:

[a.lyp.zip](https://github.com/KLayout/klayout/files/2842442/a.lyp.zip)

**Comment by klayoutmatthias** [comment]
The maximum stipple pattern height is 32. When a pattern larger than this is loaded from .lyp, this crash happens. I have limited the reader to 32 and it's safe now. But the pattern is clipped. To allow larger stipple pattern is a bigger effort.
Is this required?

**Comment by thomaslima** [comment]
I thought stipples were only 8x8. I gotta see what this is about.

On 23 Feb 2019, at 03:57, Matthias Köfferlein <notifications@github.com<mailto:notifications@github.com>> wrote:


The maximum stipple pattern height is 32. When a pattern larger than this is loaded from .lyp, this crash happens. I have limited the reader to 32 and it's safe now. But the pattern is clipped. To allow larger stipple pattern is a bigger effort.
Is this required?
