### ISSUE TITLE
salt - please use proxy

### ISSUE THREAD

**Issue by thesourcerer8** [KLayout/klayout#240]
Please use the proxy settings for salt (environment variables http_proxy and https_proxy) , some computers do not have direct internet access.

**Comment by klayoutmatthias** [comment]
Sorry, I'm just taking what Qt gives me. There aren't many options and according to their documentation they will take the system's settings. I can confirm this on the systems I have access to. I just observe long response times on Windows, but I could pin this down to some versions of openssl.

Matthias

**Comment by klayoutmatthias** [comment]
Any updates? I'll close this issue otherwise.
