### ISSUE TITLE
Launching KLayout from Windows CMD

### ISSUE THREAD

**Issue by thomaslima** [KLayout/klayout#260]
I have tried to run the `klayout_app.exe` from the windows CMD with a python script "-r" option and although it seem to have worked, it did not print anything to stdout.

Is this a bug or a limitation of windows? (cf. https://stackoverflow.com/questions/54536/win32-gui-app-that-writes-usage-text-to-stdout-when-invoked-as-app-exe-help)

**Comment by FriendFX** [comment]
I believe this may have already been answered in this discussion, which seems to reflect what's been said in your SO link:
https://www.klayout.de/forum/discussion/comment/4000#Comment_4000

**Comment by thomaslima** [comment]
Thank you!
