### ISSUE TITLE
Silent ignoring macros written on unsupported language

### ISSUE THREAD

**Issue by EugeneZelenko** [KLayout/klayout#272]
I tried to add [tf_import](https://github.com/klayoutmatthias/tf_import) (Ruby script) to KLayout 0.25.4 built with only Python support. KLayout silently ignored macro, but I think it'll be reasonable to notify user about unsupported language.

**Comment by klayoutmatthias** [comment]
The closes to "noisy" (as opposite to silent) I can do is to issue a message on stderr and in the log window. I don't want to pop up a modal dialog because of this. 

Any concerns?

**Comment by EugeneZelenko** [comment]
Log file should be fine. Probably macros on unsupported languages should not be added into GUI.

**Comment by EugeneZelenko** [comment]
Thank you for help!
