### ISSUE TITLE
PyCharm and klayout.Qt*

### ISSUE THREAD

**Issue by brunotaglietti** [KLayout/klayout#291]
Hi,

I am a python beginner and I was able to get PyCharm to create a gds file with basic DPolygons and DBoxes. But for some reason I can't get it to import the Qt modules.

It imports pya, klayout.{db, tl, rdb} with no issue. However, it can't find any of:
from klayout.QtCore import *
from klayout.QtGui import *
from klayout.QtWidgets import *
from klayout.lay import *

My goal is to ultimately use the SiEPIC library within pycharm. Please help.

**Comment by klayoutmatthias** [comment]
I think you're using the klayout package from pypi. This does not come with klayout.Qt*. 

I'm no pycharm user, but apparently you can configure it to use KLayout as interpreter (```klayout -b -r script.py```).

But please don't post questions here. This is an issue tracker. Go to the forum (www.klayout.de/forum).

I'll close this ticket.
