### ISSUE TITLE
Cannot display the right icon in Ubuntu

### ISSUE THREAD

**Issue by chriswcy** [KLayout/klayout#294]
Cannot display the right icon in Ubuntu. Finally, I found that the icon file name should be "klayout" in "/usr/share/applications/klayout.desktop" but the actual file name in "/usr/share/pixmaps" is "logo.png". I simply fixed it by renaming the png file name to "klayout.png".

I guess this file is related to "klayout/etc/logo.png" of the repository. I suggest simply rename the file name to "klayout.png" as I did in Ubuntu.

**Comment by klayoutmatthias** [comment]
Thanks for reporting this. I'm fixing that.

Regards,

Matthias
