### ISSUE TITLE
KLayout for MacOS Catalina

### ISSUE THREAD

**Issue by VictorShishkin** [KLayout/klayout#297]
Hello! A week ago I upgraded my OS to MacOS Catalina Beta, and now KLayout stopped working... I didn't expect there will be compatibility issue.
I really hope there will be update of KLayout for Catalina. It's a really great software!

<img width="423" alt="Screen Shot 2019-07-04 at 16 52 48" src="https://user-images.githubusercontent.com/47693502/60649414-e6fd3d00-9e7c-11e9-9650-cd38b262130c.png">

**Comment by calebjordan** [comment]
@Kazzz-S Do you have any ideas here? 

Some of us live on the bleeding edge and often suffer for it…

**Comment by VictorShishkin** [comment]
These are problem details:

Process:               klayout [1153]
Path:                  /Applications/klayout.app/Contents/MacOS/klayout
Identifier:            de.klayout
Version:               0.25.9 (0.25.9)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           klayout [1153]
User ID:               502

Date/Time:             2019-07-12 02:31:23.136 +0900
OS Version:            Mac OS X 10.15 (19A501i)
Report Version:        12
Anonymous UUID:        6E0E9164-C6FE-4DFE-637F-FDEC9B7FDA56

Sleep/Wake UUID:       37E92EFE-68DB-451F-84C8-92C2B82A284F

Time Awake Since Boot: 16000 seconds
Time Since Wake:       15000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/libruby.2.3.0.dylib
  Referenced from: /Applications/klayout.app/Contents/MacOS/klayout
  Reason: image not found

Binary Images:
       0x10ce6a000 -        0x10ce75ffb +de.klayout (0.25.9 - 0.25.9) <FC66FD5D-BC69-3A45-AB07-4DDA2193E838> /Applications/klayout.app/Contents/MacOS/klayout
       0x11afcc000 -        0x11b05a81f  dyld (729) <B762DAD0-A0A4-3B06-A17D-BC9C1774A30B> /usr/lib/dyld
    0x7fff3ac01000 -     0x7fff3acf4fff  org.python.python (2.7.16 - 2.7.16) <2A013D34-6B3E-3526-80BB-6BC07D6F8868> /System/Library/Frameworks/Python.framework/Versions/2.7/Python

Model: MacBookPro12,1, BootROM 186.0.0.0.0, 2 processors, Intel Core i5, 2.9 GHz, 8 GB, SMC 2.28f7
Graphics: kHW_IntelIris6100Item, Intel Iris Graphics 6100, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1867 MHz, 0x80AD, 0x483943434E4E4E424C54424C41522D4E5544
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1867 MHz, 0x80AD, 0x483943434E4E4E424C54424C41522D4E5544
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x133), Broadcom BCM43xx 1.0 (7.77.97.1 AirPortDriverBrcmNIC-1424)
Bluetooth: Version 7.0.0d97, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0512G, 500.28 GB
USB Device: USB 3.0 Bus
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1


And here is a line from Apple system log:
Jul 12, 2019 2:31:23 Problem Reporter[1155]: assertion failed: 19A501i: libxpc.dylib + 87248 [5321C905-18A7-3566-9831-441CCFC2E794]: 0x89


I hope it's helpful

**Comment by Kazzz-S** [comment]
@calebjordan Thank you for your comment. @VictorShishkin Thank you for providing detailed information.
I've tried to install **Catalina Beta** version in my VMware environment but failed in my first trial, unfortunately :-(  My real work environment is STILL Yosemite; far behind a bleeding-edge!

By the way, which binary package have you tried? I guess it's **klayout-0.25.9-macOS-Mojave-1-Qt5124mp.dmg**. Including this, those DMGs provided via the KLayout site are built to dynamically link OS-bundled Ruby and Python.

> Dyld Error Message:
> Library not loaded: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/libruby.2.3.0.dylib
> Referenced from: /Applications/klayout.app/Contents/MacOS/klayout
> Reason: image not found

Above error message suggests that the expected Ruby library (used in Mojave) is missing or most likely a different version of Ruby is bundled in Catalina. Could you please provide the version information about **Ruby and Python in Catalina** (I hope they exist) under:

``
/System/Library/Frameworks/Ruby.framework
``
and 
``
/System/Library/Frameworks/Python.framework
``

With warm regards,
Kazzz

**Comment by calebjordan** [comment]
@Kazzz-S , does this help?

```
ls /System/Library/Frameworks/Ruby.framework/Versions 
2.6     Current
ls /System/Library/Frameworks/Python.framework/Versions
2.3     2.5     2.6     2.7     Current
```

**Comment by Kazzz-S** [comment]
Hi @calebjordan,

Thanks. It looks that Ruby's version is **2.6**. 
Are you using KLayout with Ruby automation (RBA)?
I have built a special DMG on Mojave **disabling Ruby**, which is available at:
  https://www.dropbox.com/sh/qeny6se8fepgois/AACnthqtYTGxN78XhF02rav3a?dl=0
for experimental purpose. Please just try this package and see what would happen on Catalina.
If you do not need RBA, this can be a lazy solution :-)

With warm regards,
Kazzz
(Please refer to the next comment, too.)

**Comment by Kazzz-S** [comment]
### About two different DMG packages ###
![KL0259-Mojave-Ruby-ON](https://user-images.githubusercontent.com/16847255/61120644-67a0e680-a4d8-11e9-906e-a2b71e4ae965.png)
![KL0259-Mojave-Ruby-OFF](https://user-images.githubusercontent.com/16847255/61120763-a767ce00-a4d8-11e9-9f8f-5cb1f92827de.png)

----
### Sample Images ###
![Sample-01](https://user-images.githubusercontent.com/16847255/61120871-dda54d80-a4d8-11e9-9bb6-fc5dcf96ef5a.png)
![Sample-02](https://user-images.githubusercontent.com/16847255/61120876-e138d480-a4d8-11e9-86ea-bcbe7234bbfa.png)

-----
### Ruby cannot be used ###
![Ruby-01](https://user-images.githubusercontent.com/16847255/61120987-1d6c3500-a4d9-11e9-84d4-e29697cbfcf7.png)

----
### But Python (2.7.x) can be used ###
![Python-01](https://user-images.githubusercontent.com/16847255/61121018-2f4dd800-a4d9-11e9-8f3c-86ec38134e94.png)
![Python-02](https://user-images.githubusercontent.com/16847255/61121029-34ab2280-a4d9-11e9-8743-f801ba94aba7.png)
![Python-03](https://user-images.githubusercontent.com/16847255/61121041-38d74000-a4d9-11e9-99c1-9478e0d3e0d0.png)

**Comment by calebjordan** [comment]
@Kazzz-S, it worked! I only ever use the Python interpreter anyway. 

Thanks so much for the help!

**Comment by VictorShishkin** [comment]
Awesome! It worked for me too! Thank you so much, @Kazzz-S!
Feels so good to work with KLayout again!

**Comment by klayoutmatthias** [comment]
Good to hear this!  :-)

I'll close this issue then.
