### ISSUE TITLE
CIF, error when changing layer name while file open in KLayout

### ISSUE THREAD

**Issue by electronum** [KLayout/klayout#322]
The error appears whenever: the cell layer name `L <name>;` is changed to a new layer name not yet present in the file (while opened) and reloading it in KLayout.

The error does not occur when closing and re-opening the file.

Tested in KLayout Viewer and Editor 0.25.8 and 0.25.9

> Internal error: ../../src/db/db/dbLayout.cc:1616 m_layer_states [index] == Free was not true (line=2, Cell=C1)

![LayerError](https://user-images.githubusercontent.com/25344206/63155863-c09df600-c013-11e9-8c92-c74d20ecbb12.png)

# Minimum working example
```
DS 1 100 1;
L L0;
B 100 50 0 0;
DF;

E
```
[LayerTest.zip](https://github.com/KLayout/klayout/files/3508825/LayerTest.zip)

# Steps to reproduce
* Open file in KLayout
* Change the layer `L L0;` to something else (example `L L1;`)
* Save the file
* Confirm reloading the file in KLayout

**Comment by klayoutmatthias** [comment]
Thanks for this nicely prepared bug report :-)

**Comment by electronum** [comment]
no problem :ok_hand:
