### ISSUE TITLE
Feature request: Ruler Property Editor for "LayoutView::create_measure_ruler()"

### ISSUE THREAD

**Issue by Kazzz-S** [KLayout/klayout#342]
This is related to both:

1. https://github.com/KLayout/klayout/issues/333
and
2. https://github.com/KLayout/klayout/pull/335

The newly added feature **LayoutView::create_measure_ruler()** is extremely powerful and useful as I expected! Thank you very much for providing this.

To further enhance this feature, I would like to have an enhanced **Ruler Property Editor** with a GUI something like below. I hope the GUI is self-explanatory.

![RulerPropertiesPage-Automeasure](https://user-images.githubusercontent.com/16847255/64076009-8febdb00-ccfa-11e9-80cb-a7e9476d7562.png)

I'm preparing a separate test report regarding **LayoutView::create_measure_ruler()** https://github.com/KLayout/klayout/issues/341 where some issues captured through a kind of stress test will be described.

To me, it seems that the issues are (perhaps) related to the deep part of the "auto measure algorithm."
The implementation of **LayoutView::create_measure_ruler()** that wraps the algorithm looks fine.

I think this enhanced GUI should help debug the issues, too.

With warm regards,
Kazzz

**Comment by klayoutmatthias** [comment]
Hi Kazzz,

thanks for this suggestion. I striving for generic functionality with as many use cases as possible. So I'd like to modify the proposal somewhat. Here is an idea:

![Screenshot from 2019-09-01 23-19-19](https://user-images.githubusercontent.com/25720841/64082421-0266b600-cd0f-11e9-87f4-c45fc5a4ffa5.png)

"Swap points" would swap P1 and P2 (a function I wanted myself). "Snap to layout" would snap P1, P2 or both to layout edges.

The seed points would be P1 and P2 then. If you set P1 = P2, the effect is the same as for "create_measure_ruler". All these buttons imply "Apply".

You can try this solution in the "issue-342" branch.

Best regards,

Matthias

**Comment by Kazzz-S** [comment]
Hi Matthias,

Thank you again for your positive and prompt action.
Your idea is fine with me. "Swap points" is the one I want, too!

I'll try the branch.

With warm regards,
Kazzz

**Comment by Kazzz-S** [comment]
Hi Matthias,

I've confirmed that the new GUI in the "issue-342" branch works as you described.
It's fascinating and makes my job easy!

With best regards,
Kazzz
