### ISSUE TITLE
how to convert cadence tf file to lyp？

### ISSUE THREAD

**Issue by 245950258** [KLayout/klayout#347]
I am new to klayout.
Does klayout have this feature that converting tf file to lyp.

**Comment by klayoutmatthias** [comment]
Hi,
this is an issue tracker, not a place to ask questions. Please use the KLayout forum: https://www.klayout.de/forum

And simply googling "klayout cadence techfile" finds you this: https://github.com/klayoutmatthias/tf_import 

Matthias
