### ISSUE TITLE
file-path and rdb-file behavior is inconsistent

### ISSUE THREAD

**Issue by EugeneZelenko** [KLayout/klayout#353]
When session is loaded with -u layout files as loaded from same directory as session file, but rdb-file is loaded from current working directory. This leads to problem when path in -u and current working directory are different.

Workaround is to use absolute or relative path in rdb-file, but I think will be good idea if KLayout behavior will be consistent in both cases.

**Comment by klayoutmatthias** [comment]
Good point. Makes sense.

Matthias

**Comment by EugeneZelenko** [comment]
Sorry, I forgot to mention that I meant that both file-path and rdb-file are just file names without path.

**Comment by klayoutmatthias** [comment]
I also noticed that L2N and LVS DB are not included in the sessions. This is inconsistent as RDB's are. I have fixed this as well.

**Comment by EugeneZelenko** [comment]
Thank you for quick fix!
