### ISSUE TITLE
Search in user properties

### ISSUE THREAD

**Issue by EugeneZelenko** [KLayout/klayout#383]
It'll be great to extend search capabilities to content of user properties.

**Comment by klayoutmatthias** [comment]
Hi Eugene,

you mean "Search and Replace"? 

It's already possible to search by user properties: you can use a custom query (go to "Custom" page) like this:

```
shapes from instances of ... where shape.property(1) == 17
```

This searches for shapes the as-if-flat layout (recursively) where the user property '#1' has the numeric value of 17.

This feature has manifold options. For example to search by property string with a glob expression, use:

```
shapes from cells * where shape.property(42) ~ "C*"
```

This search will give you all shapes from all cells (reported per cell) where the string value of user property '#42' will start with an upper case letter "C".

More details can be found here: https://www.klayout.de/doc-qt4/about/custom_queries.html

Matthias

**Comment by EugeneZelenko** [comment]
Hi, Matthias!

Sorry, I was not aware about power of custom searches and thought about expansion of options in Find _X_ pages  :-( Just to clarify for my application, do shapes include paths?

**Comment by klayoutmatthias** [comment]
Hi Eugene, 

Yes, paths are also shapes.

Matthias

**Comment by klayoutmatthias** [comment]
Can I close this issue?

**Comment by EugeneZelenko** [comment]
Sure.
