### ISSUE TITLE
No more "rename cell" in hierarchy browser context menu?

### ISSUE THREAD

**Issue by mguthaus** [KLayout/klayout#427]
The documentation shows that this option exists (in 0.24 at least):
https://www.klayout.de/0.24/doc/manual/rename_cell.html
but in 0.26, I cannot seem to find the option as shown here:
![image](https://user-images.githubusercontent.com/12450095/69385258-98a5da80-0c73-11ea-84ac-7508e2deac6e.png)

**Comment by klayoutmatthias** [comment]
Maybe you're in viewer mode? "Rename cell" is only there in editor mode.

Matthias

**Comment by mguthaus** [comment]
I did not realize there was a separate edit mode. Thanks!
