### ISSUE TITLE
Is KLayout at FOSDEM?

### ISSUE THREAD

**Issue by mithro** [KLayout/klayout#488]
Hi!

Sorry, I wasn't sure what the best way to contact you was. I was wondering if anyone from the KLayout project was attending FOSDEM? I would love to chat with anyone involved in the project around efforts I'm doing regarding open source PDKs.

Tim '@mithro' Ansell

**Comment by klayoutmatthias** [comment]
Hi Tim,

not FOSDEM, I'm afraid. But I'm going to be at another conference, FSiC, which is taking place in June (4th to 6th) in Zurich (https://wiki.f-si.org/index.php/FSiC2020). Open source PDKs are a very important topic IMHO and I'd love to chat about that.

Best regards,

Matthias

**Comment by klayoutmatthias** [comment]
P.S. you could post such topics in the KLayout forum (https://www.klayout.de/forum)
