### ISSUE TITLE
Object cannot be created here in QWidget_Native.show

### ISSUE THREAD

**Issue by tkoyat** [KLayout/klayout#490]
import ......
from lay import *
if __name__ == "__main__":
    app = QApplication(sys.argv)
    try:
        form = MainWindow()
        form.show()
        sys.exit(app.exec_())
    except Exception as e:
        print(e)

debug: <klayout.lay.MainWindow object at 0x000001F2DDB50B40>

**Comment by tkoyat** [comment]
Hi Matthias:
how to use lay show MainWindow?

**Comment by klayoutmatthias** [comment]
Closed as duplicate of #479.
