### ISSUE TITLE
DRC reports duplicated width check violations

### ISSUE THREAD

**Issue by Mitsuhide-T** [KLayout/klayout#512]
Hi Matthias,

I'm testing my simple width check DRC on version 0.25.9 and version 0.26.3.
Please refer to the attached ZIP file [widthcheck.zip](https://github.com/KLayout/klayout/files/4247704/widthcheck.zip) that contains eight files listed in the table below.

The expected number of width check violations is 28=14x2. 
The results using version 0.25.9 is 28 as expected. However, version 0.26.3 reports 38 with 10 duplications.

|Srl.No.|File Name|Contents|
|:------:|:--------:|:--------------:|
1-1|widthcheck_0.25/widthcheck.lys|Session file|
1-2|widthcheck_0.25/widthcheck.oas|Test design in OASIS|
1-3|widthcheck_0.25/widthcheck.lydrc|Simple DRC macro|
1-4|widthcheck_0.25/widthcheck.lyrdb|Report database|
2-1|widthcheck_0.26/widthcheck.lys|Session file|
2-2|widthcheck_0.26/widthcheck.oas|Same as 1-2|
2-3|widthcheck_0.26/widthcheck.lydrc|Same as 1-3|
2-4|widthcheck_0.26/widthcheck.lyrdb|Report database|

The target polygon in the 0/1 layer has 14 notches and each notch has two rectangular bumps (<20um).
![img01](https://user-images.githubusercontent.com/60456341/75207909-6bf6e700-57bd-11ea-83de-f790ad4b5180.png)
![img02](https://user-images.githubusercontent.com/60456341/75207914-70bb9b00-57bd-11ea-946e-e7bd6c493e94.png)

> My simple DRC.
```
report("Simple DRC")
lay = 0
dty = 1
val = 20.um
inlayer = input( lay.to_i, dty.to_i )
categoryNameWidth = "width check " + val.to_s + "um"
inlayer.width( val, projection ).output( categoryNameWidth )
```
> Results

**version 0.25.9 returns 28 edge pairs.**
![result-0 25 9](https://user-images.githubusercontent.com/60456341/75207957-8c26a600-57bd-11ea-804b-2d5f41ddbce4.png)

**version 0.26.3 returns 38 edge pairs.**
![result-0 26 3](https://user-images.githubusercontent.com/60456341/75207965-90eb5a00-57bd-11ea-978b-2b719f467543.png)

My platform. 
Linux Mint 19 is based on Ubuntu18.04 LTS.
![platform](https://user-images.githubusercontent.com/60456341/75207979-9779d180-57bd-11ea-8a30-556a14ff39b9.png)

Thanks.
Mitsuhide

**Comment by Kazzz-S** [comment]
Here are two more cases tested on Mac.

### Version 0.26.3 on Catalina reports 35 (with duplications) violations. ###
![Catalina-0263](https://user-images.githubusercontent.com/16847255/75232249-3c1a0480-57fa-11ea-96fd-6e485377dac0.png)

### Version 0.25.9 on Yosemite reports 28 (correct) violations. ###
![Yosemite-0259](https://user-images.githubusercontent.com/16847255/75232255-3fad8b80-57fa-11ea-8e37-3612e17f99e6.png)


Mitsuhide, my colleague, is supposed to add some Valgrind results later.

Regards,
Kazzz

**Comment by klayoutmatthias** [comment]
Thanks a lot for this nice bug report!

I'll take a look asap. I need a little time.

Best regards,

Matthias

**Comment by klayoutmatthias** [comment]
Hi kazzz, hi Mitsuhide,

The bug you found is another effect of issue #481 (although your bug report is much better than mine!).

This bug is already fixed in master branch and the fix will be released soon (there is only #482 on my list for 0.26.4). I could confirm your issue is no longer seen on the master branch.

Best regards,

Matthias

**Comment by Kazzz-S** [comment]
Hi Matthias,

Thanks for your prompt response.
I have built the master branch f1aca46a on **macOS Catalina** and confirmed that the issue had been fixed.
![Issue512-Catalina](https://user-images.githubusercontent.com/16847255/75433971-2f311880-5994-11ea-84f5-49b48e41d0f7.png)

Mitsuhide is going to test the same branch on the Linux.

With warm regards,
Kazzz

**Comment by Mitsuhide-T** [comment]
Hi Matthias,

I have built the master branch(download the zip on 2020-02-28) on Linux Mint 19.1 and confirmed that the issue had been fixed.
So I'm closing this issue. 
![mint19-KLayout-master](https://user-images.githubusercontent.com/60456341/75503469-0dc64000-5a19-11ea-988c-4e969e1be7db.png)

I'm looking forward to the next version.

Kind regards,
Mitsuhide
