### ISSUE TITLE
RuntimeError: Cannot determine format from filename in SaveLayoutOptions.set_format_from_filename

### ISSUE THREAD

**Issue by tkoyat** [KLayout/klayout#513]
I used the packaging tool pyinstaller to package the code, causing a format problem:

Traceback (most recent call last):
  File "1.py", line 27, in <module>
    value = opt.set_format_from_filename(file_gds)
RuntimeError: Cannot determine format from filename in SaveLayoutOptions.set_format_from_filename
[7023] Failed to execute script 1

**Comment by klayoutmatthias** [comment]
What is the value of "file_gds"?

**Comment by klayoutmatthias** [comment]
I think the problem is related to the pyinstaller tool and the way it packages the libraries. It does not package the dynamically-linked stream reader plugins. 

Please don't use pyinstaller. Use setup.py/distutils instead.

Matthias
