### ISSUE TITLE
SiEPIC tools is not available

### ISSUE THREAD

**Issue by kavehrahbardar** [KLayout/klayout#556]
SiEPIC-tools package is not available in the salt package manager.

**Comment by klayoutmatthias** [comment]
I do see it ...

![image](https://user-images.githubusercontent.com/25720841/82253262-ef554e00-9950-11ea-8b9b-747b94b51a26.png)

Maybe a temporary glitch? Please check again.

Matthias

**Comment by klayoutmatthias** [comment]
Any updates? I'll close the ticket otherwise.

**Comment by lukasc-ubc** [comment]
works for me.

**Comment by kavehrahbardar** [comment]
Thanks Matthias,

Works now. I think it was a glitch at that time.

Thanks,
