### ISSUE TITLE
KLayout 0.26.5 for macOS Catalina with Anaconda3/Homebrew

### ISSUE THREAD

**Issue by Kazzz-S** [KLayout/klayout#557]
This ticket is to address the issue raised in https://github.com/KLayout/klayout/issues/552#issuecomment-626460971.

I have rebuilt another DMG modifying the build-environment for macOS assuming the following conditions:
1. Anaconda3 is installed under $HOME/opt/anaconda3
2. There is a symbolic link: /Applications/anaconda3 ---> $HOME/opt/anaconda3/
3. **ruby** has been installed by ```conda install ruby```
4. **PYTHONHOME** environment variable is set to **/Applications/anaconda3**

Please refer to the images below.

![A1-Anaconda1](https://user-images.githubusercontent.com/16847255/82113826-dd7a7c00-9793-11ea-8dc1-64c884e198e6.png)

![A2-condaVer](https://user-images.githubusercontent.com/16847255/82113833-e3705d00-9793-11ea-8ce1-39ef641fddd0.png)

![A3-QtVer](https://user-images.githubusercontent.com/16847255/82113837-e8351100-9793-11ea-8d73-6193c378415a.png)

![A4-KLVer](https://user-images.githubusercontent.com/16847255/82113839-ecf9c500-9793-11ea-9a84-b09ee5fe9bad.png)

![A5-PYTHONHOME](https://user-images.githubusercontent.com/16847255/82113844-f125e280-9793-11ea-8a12-954041e35226.png)

![A6-import](https://user-images.githubusercontent.com/16847255/82113846-f5520000-9793-11ea-8070-920422a4c95f.png)

**Comment by Kazzz-S** [comment]
Dear  @lukasc-ubc,

I have uploaded the second DMG (LW-klayout-0.26.5-macOS-Catalina-2-qt5Ana3-Rana3Pana3.dmg) under [0.26.5-Tests](https://www.dropbox.com/sh/zy0pdmdg08uyiw4/AAAJvIpa6q9A9hTMCIKFFTXOa?dl=0).

Please try this one if you have time.

Regards,
Kazzz-S

**Comment by siepic** [comment]
I have downloaded

> Dear @lukasc-ubc,
> 
> I have uploaded the second DMG (LW-klayout-0.26.5-macOS-Catalina-2-qt5Ana3-Rana3Pana3.dmg) under [0.26.5-Tests](https://www.dropbox.com/sh/zy0pdmdg08uyiw4/AAAJvIpa6q9A9hTMCIKFFTXOa?dl=0).
> 
> Please try this one if you have time.
> 
> Regards,
> Kazzz-S

Dear @Kazzz-S 

That works!  The way to put an environment variable and make it available system-wide, is

`launchctl setenv PYTHONHOME "/Applications/anaconda3"`

You could add that to your instructions (4) above, since it took me some searching to figure that out.

**Comment by Kazzz-S** [comment]
> Dear @Kazzz-S
> 
> That works! The way to put an environment variable and make it available system-wide, is
> 
> `launchctl setenv PYTHONHOME "/Applications/anaconda3"`
> 
> You could add that to your instructions (4) above, since it took me some searching to figure that out.

Hi,

Thank you for testing the DMG package and sharing the idea to set the environment variable.

----
The Dropbox directory mentioned above includes a ZIP file `script-bundles.zip` that contains a sample Bash script bundle `KLayoutAna3.app` generated by using the OS tool **Autometer.app**. The contents are shown below.

To use this script bundle, you need to rename `/Applications/klayout.app` to `/Applications/klayout-ana3.app` after installing the DMG package.
**KLayoutAna3.app** uses its own configuration file (klayoutrc-ana3) to coexist with the
standard package that uses the OS-bundled Ruby and Python (2.7).

```
#!/bin/bash
#-------------------------------------------------------------------------------------
# Bundle: KLayoutAna3.app
#
# Descriptions:
#  This is to invoke "klayout-ana3.app" using Anaconda3 distributed as
#  a binary package for Mac in "editor" mode.
#-------------------------------------------------------------------------------------

#---------------------------------------------------------
# Export 'PYTHONHOME' environment variable
#---------------------------------------------------------
export PYTHONHOME=/Applications/anaconda3

#---------------------------------------------------------
# With "-n" option, multiple instances can be invoked
#---------------------------------------------------------
myconfig=$HOME/.klayout/klayoutrc-ana3

open -n -a /Applications/klayout-ana3.app --args -e -c $myconfig -style=fusion $@
```

I should have added this.
Regards,
Kazzz-S

**Comment by Kazzz-S** [comment]
I have rebuilt two DMGs with some updates, which are available under [this Dropbox directory](https://www.dropbox.com/sh/zy0pdmdg08uyiw4/AAAJvIpa6q9A9hTMCIKFFTXOa?dl=0).

|DMG|Target OS|Shared Development Environment|
|:------:|:--------:|:--------:|
|LW-klayout-0.26.5-macOS-Catalina-3-qt5Ana3-Rana3Pana3.dmg|Catalina|Anaconda3|
|LW-klayout-0.26.5-macOS-Catalina-3-qt5Brew-Rhb27Phb37.dmg|Catalina|Homebrew|

These packages have an additional folder containing the support documents.

![Build3-Ana3](https://user-images.githubusercontent.com/16847255/82743023-1ae89600-9da0-11ea-9a17-3327d8091e69.png)
![Build3-Homebrew](https://user-images.githubusercontent.com/16847255/82743024-1de38680-9da0-11ea-8216-411a8ae03d45.png)

Regards,
Kazzz-S

**Comment by lukasc-ubc** [comment]
@Kazzz-S 
this works beautifully!
thanks for the bundle. I like the script bundle and icon.

**Comment by Kazzz-S** [comment]
@lukasc-ubc 

Thank you for testing the new package.
Glad to hear that you liked it.
I close this ticket with this comment.

Kazzz-S
