### ISSUE TITLE
Perimeter contribution to area for antenna DRC checks

### ISSUE THREAD

**Issue by klayoutmatthias** [KLayout/klayout#570]
Some design rules require the antenna area to be computed by taking the perimeter into account. So the effective metal area is:

```
Aeff = A + d * P
```

(A is the metal area, P the perimeter and d some "thickness").

Right now, this perimeter contribution can't be included.

**Comment by Fatsie** [comment]
In the TSMC tecnology I am using now, the antenna ratio is defined by only using the perimeter of the metal and only the area of the gate. I don't think your fix can handle using perimeter only of the metal in the drc. I only see area_only() and area_and_perimeter(), not perimeter_only().
