### ISSUE TITLE
Import pya module outside of Klayout

### ISSUE THREAD

**Issue by acbg** [KLayout/klayout#618]
I'm trying to run a python script (where I import a library, create a layout and a gds file) from `vim` instead of using the klayout own editor and compiler, but python can't find the `pya` module. I'm in linux (arch or ubuntu) but can't seem to find where the klayout modules are located... Where can I find it and how do I import it?

**Comment by klayoutmatthias** [comment]
pya is not a standalone module, it's only available inside KLayout as it provides the API to the application. It's not a library.

You can use "klayout" from pip if you're happy with a subset of the features.

Matthias
