### ISSUE TITLE
Cannot launch on centOS8

### ISSUE THREAD

**Issue by yuelyao** [KLayout/klayout#636]
klayout-0.26.4-0.x86_64 is successfully installed on centos8 with an rpm but when launch it, meet the following message and nothing more:

Info: Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Aborted (core dumped)

What is the problem, does anyone know how to fix it?
Thanks very much!

**Comment by klayoutmatthias** [comment]
Have you tried setting QT_QPA_PLATFORM=wayland as the error message suggests?

**Comment by klayoutmatthias** [comment]
I'll close this issue as there is no response.
