### ISSUE TITLE
Unable to open KLayout 0.26.8

### ISSUE THREAD

**Issue by honeysh08** [KLayout/klayout#667]
Even after Klayout0.26.8 has been built successfully on Cent OS 7, the application is not being installed. Also, it cannot be opened using terminal. 

also, this message is being displayed.
Warning: klayout: cannot connect to X server

**Comment by klayoutmatthias** [comment]
This is not a KLayout bug. This message is issued by the X11 client library.

Possible reasons:
* $DISPLAY not set
* No permission to connect to the display
* No X11 server on the client side (e.g. when starting from WSL)

As this is not related to KLayout, I'll close this issue.
