### ISSUE TITLE
Argument order inconsistency

### ISSUE THREAD

**Issue by mguthaus** [KLayout/klayout#671]
The usage says:
`klayout [<options>] [<file>] ..
options
...
   -m <database file>  Load RDB (report database) file (into previous layout view)`
However, when I run a command like this:
`klayout -m foo.drc.results foo.gds`
it does not load the results file. Instead, I have to run:
`klayout foo.gds -m foo.drc.results`
to get it to work. 

I am using KLayout 0.27 on Ubuntu 18.04.

**Comment by klayoutmatthias** [comment]
Hi Mathew,

Unlike the "global" options, "-m" is specific to a certain view. The "-m" options is applied to layout before "-m" and the corresponding marker database is attached to the view for this layout. Basically it's possible to list multiple layouts on the command line and correspondingly you should be able to use "-m" multiple times to attach different report databases.

A more elaborate documentation of the command line options is found here: https://www.klayout.de/command_args.html

Matthias
