### ISSUE TITLE
How to select polygon by the number of box enclosed in DRC check? 

### ISSUE THREAD

**Issue by Zwlzzm** [KLayout/klayout#695]
Dear @klayoutmatthias,

Thank you for  providing so useful function for DRC.

I have  2 questions when doing DRC check and seek for your help and suggestions.

1.  How to select polygons if they has only one box of another layer?
 I could find way to achieve it.
2. The function of klayout DRC is  strong, and it achieves almost all the requirement,  however, for larger gds file (about 500M),
it is always very slow, and sometimes it cannot came out results in 1 way.  Is there any way to make it faster?

Looking forward to hearing from you!

Best regards!

**Comment by klayoutmatthias** [comment]
Hi,

I'd appreciate if you could take such requests to the Forum: https://www.klayout.de/forum/

This is a bug tracker and not intended for support requests. 

Regarding the DRC performance:
* there is the tiling option (see https://www.klayout.de/forum/discussion/comment/5278#Comment_5278) and https://www.klayout.de/doc-qt5/manual/drc_runsets.html#h2-639
* you can try (somewhat experimental) hierarchical mode: https://www.klayout.de/doc-qt5/manual/drc_runsets.html#h2-718

For the polygon selection issue there is no simple solution for 0.26. With the next major release (0.27) you will be able to specify a count on "interact" which triggers interaction for a certain range of shape count the subject interacts with.

Matthias

**Comment by Zwlzzm** [comment]
Dear&nbsp; Matthias,


Thank you for respond and kindness.
When I sign up for klayout for the first time, there is not a button "New discussion", so I think I cannot put questions in klayuout website.&nbsp; I am sorry for it and&nbsp; I will put question on the Forum"https://www.klayout.de/forum/" next time


For the first question, I have add those lines to the DRC script as what you suggested.
But it is stuck&nbsp;&nbsp;(the results cannot come out in 30 minutes)&nbsp;when it comes to 99%，no matter I change thread to 24 or 35, which is the maximum thread which the computer can support.&nbsp;
And it is still stuck (the results cannot come out in 30 minutes) when I&nbsp; change titles(titles=500,1000,2000,5000)
Do you have any other suggestions for this situation？




Generally, how long does it take do run verification for a large gds (about 600M) for you? Or in other words, if the running time is greater than how many minutes, we think it is stuck and the results cannot come out again?












For the second question，I will look forward to the 0.27 version released by you.




Wish you a happy new year！


Best regards!
Weiling



------------------ 原始邮件 ------------------
发件人:                                                                                                                        "KLayout/klayout"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月28日(星期一) 凌晨2:49
收件人:&nbsp;"KLayout/klayout"<klayout@noreply.github.com&gt;;
抄送:&nbsp;"Weiling"<2811205113@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [KLayout/klayout] How to select polygon by the number of box enclosed in DRC check?  (#695)





 
Hi,
 
I'd appreciate if you could take such requests to the Forum: https://www.klayout.de/forum/
 
This is a bug tracker and not intended for support requests.
 
Regarding the DRC performance:
  
there is the tiling option (see https://www.klayout.de/forum/discussion/comment/5278#Comment_5278) and https://www.klayout.de/doc-qt5/manual/drc_runsets.html#h2-639
 
you can try (somewhat experimental) hierarchical mode: https://www.klayout.de/doc-qt5/manual/drc_runsets.html#h2-718
  
For the polygon selection issue there is no simple solution for 0.26. With the next major release (0.27) you will be able to specify a count on "interact" which triggers interaction for a certain range of shape count the subject interacts with.
 
Matthias

**Comment by klayoutmatthias** [comment]
It's hard to say how long 600MB will take because the actual number of shapes can be huge (with a lot of hierarchy) or small (when flat). If the progress gets stuck at oo% in tiled mode with a decend tile size (i.e. 10% of the chip's width or height), then I assume it's because the DRC collected a lot of errors or huge intermediate layers.

I assume you can't send your test case, so I have no chance (as often) to debug the issue.

Matthias

**Comment by Zwlzzm** [comment]
Dear Matthias,


Sorry for the late reply.&nbsp; Does&nbsp; the“&nbsp;test case” mean both the gds file and the DRC file?
The gds file will be&nbsp; a little trouble. I will try to prepare a test gds file and send it to your email together with the&nbsp; DRC file. Can you help us test if there are methods to make the results come out then?





Best regards!
Weiling
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KLayout/klayout"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月29日(星期二) 凌晨4:21
收件人:&nbsp;"KLayout/klayout"<klayout@noreply.github.com&gt;;
抄送:&nbsp;"Weiling"<2811205113@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [KLayout/klayout] How to select polygon by the number of box enclosed in DRC check?  (#695)





 
It's hard to say how long 600MB will take because the actual number of shapes can be huge (with a lot of hierarchy) or small (when flat). If the progress gets stuck at oo% in tiled mode with a decend tile size (i.e. 10% of the chip's width or height), then I assume it's because the DRC collected a lot of errors or huge intermediate layers.
 
I assume you can't send your test case, so I have no chance (as often) to debug the issue.
 
Matthias
