### ISSUE TITLE
Object Selection larger than drawn

### ISSUE THREAD

**Issue by demisjohn** [KLayout/klayout#715]
When dragging to select multiple objects, the actual selection rectangle is invisibly larger than what is drawn on screen.
Here is a video showing this.

https://user-images.githubusercontent.com/5370181/106155261-527cbe80-6135-11eb-84d3-93105d63a884.mov

This is an array of circle-like polygons, you can see where I end the selection box, but objects are selected in an area larger than I expected.

(Klayout v. 0.26.9, Mac OS 10.14.6, MacBook Pro "MacBookPro14,2")

**Comment by klayoutmatthias** [comment]
Cool .. I did not know you can add videos too.

Maybe the circles are within an instance which is rotated?

If so, the explanation is that the selection rectangle gets transformed "into" the instance. But as it stays a rectangle it will get larger - the bounding box of a rotated rectangle is bigger than the original.

If so, I'm afraid to fix that the concept of the "selection rectangle" had to be extended to a "selection polygon". That's a more difficult topic then. Not impossible, but requires some effort.

**Comment by demisjohn** [comment]
Actually no - this is a single-cell (flattened) file.  No instances as far as I can tell.
It is a 250MB file - here is a link to the GDS in question to test the issue yourself.
https://drive.google.com/file/d/1-Hb8RgUaIyyx1mAqIFlFc7IFNe59fj8b/view?usp=sharing

**Comment by klayoutmatthias** [comment]
@demisjohn Sorry, I missed this ticket and it deserves a response.

There is a parameter called "capture range": 

![image](https://user-images.githubusercontent.com/25720841/114782237-0592a680-9d7a-11eb-9340-b58bc84088b9.png)

It expands the selection box by the specified number of pixels. If you set it 0, the captured shapes should all be inside the box selected.

Matthias

**Comment by demisjohn** [comment]
Yes that was indeed the issue - thanks!  I assume it's set greater than 0 to start because there is some case in which this is important.  This explains some confusion I have previously had over the selection-box, where I hadn't been able to always predict exactly what would be selected, requiring me to zoom in in order to do more careful selections between adjacent objects.

**Comment by demisjohn** [comment]
@klayoutmatthias 
I see the issue with the "Capture range to mouse cursor" setting:

- If it is set to 0, then clicking with the mouse is **unable to select an object**, 
- however, setting it to 0 makes Dragging a selection box **invisibly larger than drawn** on the screen.

Possibly remedies:
1) Split "capture range" into 2 separate settings: one for clicking, and one for dragging.  I assume this would be a lot of work and bug fixing.
2) Make the Selection Box, that is drawn dynamically during a Drag, draw the *real* selection window (include the capture range in what is drawn).  It should draw a larger selection box than just where you clicked to begin with. The selection box is not invisible this way, but actual behavior is the same.

**Comment by klayoutmatthias** [comment]
Solution 1 was actually easier. This is how the options look like now:

![image](https://user-images.githubusercontent.com/25720841/115144724-8be70b00-a04e-11eb-8471-34114b3e1f10.png)

The first range applies to single clicks. The second one to boxes. Default for boxes is 0 so only things really inside the box get selected.

**Comment by demisjohn** [comment]
Very nice, looks good.  Impressively fast fix!
