### ISSUE TITLE
Parallel build options?

### ISSUE THREAD

**Issue by mguthaus** [KLayout/klayout#716]
Hi Matthias,

Is there an option for multi-threaded building? Klayout takes... a long time to build. I don't see anything in the ./build.sh -h information.

Matt

**Comment by thomaslima** [comment]
Not sure it is relevant to you but I use 4 threads for building with `-option -j4`.

**Comment by klayoutmatthias** [comment]
@thomaslima Thanks for this comment.

build.sh will pass every unknown option to "make". So all "make" options are implicit "build.sh" options. "-j x" is the "make" option to perform multi-threaded builds.

Matthias

**Comment by klayoutmatthias** [comment]
I think this issue is solved.
