### ISSUE TITLE
Fails to build on Debian hppa: uses non-standard sa_restorer field of struct sigaction

### ISSUE THREAD

**Issue by jscott0** [KLayout/klayout#728]
Hi,

I'm forwarding this issue on behalf of a reporter [in Debian](https://bugs.debian.org/982251). Since merging #656 it seems like there's a hard-coded assumption that systems other than macOS and the BSDs have the sa_restorer field, but we use the GNU C Library and it doesn't provide this for hppa at least.

KLayout should test at build time whether the field exists, or set only [the fields specified by POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/functions/sigaction.html) and allow the rest to be zeroed out (perhaps with designated initializers). Note that my Linux man page says
> The sa_restorer field is not intended for application use.

**Comment by klayoutmatthias** [comment]
Thanks for reporting this issue. 

I'll use a fetch-and-modify scheme to install the signal handlers to get rid of the #ifdefs and the OS dependencies.

Matthias
