### ISSUE TITLE
Request: add layout view titles to session files

### ISSUE THREAD

**Issue by klayoutmatthias** [KLayout/klayout#737]
For the background see here: https://www.klayout.de/forum/discussion/1733/changing-layoutview-title#latest

**Comment by klayoutmatthias** [comment]
I just discovered that the title is already present in the .lys files ...

**Comment by EugeneZelenko** [comment]
Hi, Matthias!

Title are exist for view and definitely could be used with layout view contains single file. However when several files are open in same view, tab text is changed depending on currently selected file. So it's reasonable to also add title to cell views, so they also could be customized.
