### ISSUE TITLE
why klayout python package miss lay module

### ISSUE THREAD

**Issue by fzr4j** [KLayout/klayout#746]
l download klayout package from pypi.org . I can find lay module on klayout manual , but can not find at this package.
![图片](https://user-images.githubusercontent.com/34558557/110764791-6f58f580-828e-11eb-9371-2848e56c9c35.png)

**Comment by klayoutmatthias** [comment]
Hi,

There is no lay module in the PyPI package. This implies a dependency to Qt which raises deployment and legal questions, so this has been dropped from the PyPI versions. The lay module is available in the Python module packaged with the Linux installers.

Matthias

**Comment by klayoutmatthias** [comment]
Can I close this ticket?

**Comment by fzr4j** [comment]
> Can I close this ticket?

yes, thank you for reply

**Comment by fzr4j** [comment]
> Can I close this ticket?
yes , thank you for your replay
