### ISSUE TITLE
pya's QMimeData::setData(const QString &mimeType, const QByteArray &data) not working anymore for Version >=0.26.10

### ISSUE THREAD

**Issue by HolgerThyen** [KLayout/klayout#771]
Hi Mathias,
In my script, I rely on the writing of JSON data via QMimeData.
The following test works out for KLayout Version <= 0.26.9, printing "no error occured", while failing for KLayout Version >= 0.26.10 with "illegal value":
```python
import pya
def test():
  mimeData = pya.QMimeData()
  mimeData.setData("application/json",'{"test":"test"}')
  jsonData = mimeData.data("application/json");
  parseError = pya.QJsonParseError()
  document = pya.QJsonDocument().fromJson(jsonData, parseError);
  print(parseError.errorString())
  
test()
```
  Any idea, what's going wrong here?
Might this be related to the fix to #708 ?

Regards, Holger

**Comment by klayoutmatthias** [comment]
Hi Holger,

thanks for the test case.

It's actually a bug. The reason isn't setData, but data(). QByteArray results got lost during a chain of translations between QVariant and byte arrays.

I'll fix that.

Thanks,

Matthias
