### ISSUE TITLE
DRCEngine puts and print write to tty instead of stdout

### ISSUE THREAD

**Issue by ahmednofal** [KLayout/klayout#812]
puts and print write to tty instead of stdout making it not possible to read the output in a different program that calls klayout.

**Comment by klayoutmatthias** [comment]
And writing to stdout makes it impossible to see the output on Windows.

Use either:
* batch mode (klayout -b -r your.drc)
* the "strmrun" utility

**Comment by klayoutmatthias** [comment]
Closing this issue as there is no further comment.
