### ISSUE TITLE
runing slow

### ISSUE THREAD

**Issue by wolfgold** [KLayout/klayout#814]
I compiled 0.24 klayout by myself with VS2010, but the running speed of the version I compiled is much slower than the 0.24 version provided. Is there any special compilation option.

**Comment by klayoutmatthias** [comment]
Did you use a debug build maybe?

Please don't expect me to give a reasonable answer without providing any details.

BTW: 0.24 is entirely outdated.

Matthias

**Comment by wolfgold** [comment]
@klayoutmatthias Thank you very much for your reply. I have found the reason. You can just select O2 in the compilation option.I extracted part of the 0.24 source code and used Visual Studia's STL directly instead of using STLPort. WIll this affects the speed of operations such as Boolean and merge.

**Comment by wolfgold** [comment]
it's STLPort's effects.
