### ISSUE TITLE
can not use -m with multiple marker database files.

### ISSUE THREAD

**Issue by ahmednofal** [KLayout/klayout#829]
Thanks for your work on this great project.

You can not open multiple marker database files at once and you need to have only one open at a time. Whether you use the command line option -m which only accepts a single file and if you specify another it will fail to open any files altogether or if you specified multiple -m each with its own file name it would also fail to open any file with an error message saying that anything that came after the first -m is included in the marker database file name for that -m . Having multiple marker database files open at once is very helpful moving from certain DR violations to the next fairly quickly.

Also the GUI has the same issue you can only have a single marker db file open at once.
Thanks.

**Comment by klayoutmatthias** [comment]
So you want them to be joined? That's a new feature request and not a small one.

**Comment by klayoutmatthias** [comment]
No.

The marker browser dialog can handle multiple DBs. So a quick implementation (or workaround) is to open the marker browser, use the "File" menu and load the first DB, then use the same function to load the second (and third).

You can switch then between the database using the drop-down box at the top. But you cannot smoothly navigate between the databases.

Other solutions are feasible, but not trivial to implement. I don't have resources for such a topic right now.

Matthias

**Comment by ahmednofal** [comment]
Yes it works, thank you !
