### ISSUE TITLE
dbedgeprocess's process function run slow in vs2013

### ISSUE THREAD

**Issue by wolfgold** [KLayout/klayout#838]
I complied the tl and db both in version 0.27 and 0.25 via  VS2013, and remove the part of gsi. I plan to use boolean, merge and size, so I called the boolean in "dbshapeprocess" Here is the function I used.

```c++
       //m_layout was successfully read from the GDS 
	unsigned int layer_i = m_layout.insert_layer();
	db::LayerProperties tmp_layer;
	tmp_layer.layer = 1000;
	tmp_layer.datatype = 0;
	m_layout.set_properties(layer_i, tmp_layer);

	db::ShapeProcessor sp(true);
	db::BooleanOp::BoolOp op = db::BooleanOp::Xor;

        //layer1 , layer2 is layer index that needed to process
        // top is m_layout's topcell index
	sp.boolean(m_layout, m_layout.cell(top), layer1,
			m_layout, m_layout.cell(top), layer2,
			m_layout.cell(top).shapes(layer_i), op, true, true, true);
	}
```

Although I have used the optimization option "O2" in VS,  the exe compiled in release mode still takes much more time to run boolean than klayout. I noticed that the process in dbedgeprocess.cc took a lot of time. In addition, are there any other factors that affect the efficiency of this function?

**Comment by klayoutmatthias** [comment]
@wolfgold  Seriously, you cannot take out code, remove parts of it, compile that with some compiler, with some library, some kind of settings and then expect me somehow magically figure out what's going wrong.

0. This is not a bug. It's your own adventure, so please don't raise a ticket against KLayout.
1. I do not support external use of C++ API. Use on your risk and please be aware that you are legally bound to GPL. So I hope your own project is GPL'd too.
2. I do not support VS2013. I'm using VS2017 and that's the only supported compiler.
3. Performance heavily depends on the STL you're using.
4. There are more options to control performance, specifically STL runtime assertions. Study the compiler options to figure out how.

**Comment by wolfgold** [comment]
> 
Thank you for you reply,I compiled the program with mingw and it has the normal performance. I think the difference caused by STL.
