### ISSUE TITLE
Too short progress bar

### ISSUE THREAD

**Issue by Kazzz-S** [KLayout/klayout#848]
The progress bar looks too short :-)
KLayout Version: 0.27.2
Build: Source build on Linux (Mac, too)

![TooShortProgressBar](https://user-images.githubusercontent.com/16847255/123564009-a11caa80-d7f2-11eb-93ec-b44688aced17.png)

Thanks,
Kazzz-S

**Comment by klayoutmatthias** [comment]
Well, it was very long before ... :)

Actually, there are sub-progress bars too for nested operations. Previously that was stacked, but that created ugly flickers in the UI. I now arranged them horizontally to have them occupy the same height. The sub-progress bars are attached to the left of the short one.

That was a low hanging fruit to achieve a less annoying progress bar.

**Comment by Kazzz-S** [comment]
I was unaware of this change until yesterday.
Thank you for your explanation.

Kazzz-S
