### ISSUE TITLE
New Layout doesn't have a layer table

### ISSUE THREAD

**Issue by lukasc-ubc** [KLayout/klayout#859]
In KLayout 0.27.2, HW-klayout-0.27.2-macOS-BigSur-1-qt5Brew-RsysPhb38.dmg version, I do the following:

* File | New
* Technology = xxx  (e.g., EBeam)
* Initial Layers = blank (default)

Expected behaviour (as in 0.26 versions) – creates a new layout with the technology active and the layer table loaded.

Now, I see:

- T (Default)
- Blank layer table

![image](https://user-images.githubusercontent.com/15843200/124335573-942fec00-db4f-11eb-9bed-f69f65b66b0c.png)

Requires manually clicking on the technology to activate it.

Thank you
Lukas

**Comment by klayoutmatthias** [comment]
This one I can reproduce :)

Actually, the technology was not assigned.

Thanks for reporting.

Matthias
