### ISSUE TITLE
Trace All Nets->Hierarchical->ProbeNet doesn't work in 0.27.2

### ISSUE THREAD

**Issue by JinWallner** [KLayout/klayout#866]
Hi, I recently switched to 0.27.2. I can't probe net with Trace All Nets->Hierarchical->ProbeNet anymore. The Flat one works but not the Hierarchical one.

**Comment by klayoutmatthias** [comment]
Sorry, I can't confirm than.

Test layout is this: https://github.com/KLayout/klayout/blob/master/testdata/gds/t10.gds

Layer stack is this:
![image](https://user-images.githubusercontent.com/25720841/126035924-aec45667-0470-4b4c-a239-70ddcfca9907.png)

I use Tools -> Trace All Nets -> Hierarchical.

I click on "Probe" and on a relevant shape in the layout. The net gets highlighted and selected in the net browser.

OS is Ubuntu 20.

Matthias

**Comment by klayoutmatthias** [comment]
I just confirmed the issue cannot reproduced either on Windows 10, 64bit.

**Comment by JinWallner** [comment]
Hi Matthias,

Thank you for your response. I am on Windows10. It's very strange that I
can use the Hierarchical Probe on your test layout. But I tried to make a
very simple random layout with similar layers. And the probe only works
within the cell. I just can't get it to work at the Top cell. It only
highlights the whole cell instance. What do I miss here?

Thanks,

Jin

**Comment by klayoutmatthias** [comment]
Hi Jin,

maybe it's possible to share the layout and the layer stack you're using? I'd like to investigate the issue.

Matthias

**Comment by JinWallner** [comment]
Hi Matthias,

Here is my test layout.
https://github.com/JinWallner/public/blob/master/test.gds
I drew random shapes with layer 3, 5, 6, and I defined the same
connectivity as your example. But somehow the net race only works in the
cell "a" but not the cell "Top".

Thanks,

Jin

**Comment by klayoutmatthias** [comment]
Hi Jin,

thanks for the sample. I see the problem.

The reason is actually that the "a" subcell does not have a pin leading to the TOP cell. This means that although instantiated in the layout, the "a" cell is not a subcircuit of "TOP" in the netlist. So eventually the layout and netlist hierarchy does not match.

I'll see if I can rectify the problem. This will need a special kind of subcircuit without a pin.

Thanks and best regards,

Matthias
