### ISSUE TITLE
Diff and XOR Tool layout selection drop down menus don't work

### ISSUE THREAD

**Issue by ottumm** [KLayout/klayout#890]
KLayout 0.27.3
macOS 11.3.1 (Big Sur) on Apple M1 ARM chip

Steps to reproduce:

1. Open two GDS files in KLayout
2. Tools -> Diff Tool
3. Click the drop down next to Layout A or Layout B

Results:

Clicking the drop down shows only a single option (both Layout A and Layout B show the same options) and so I cannot choose a second layout to diff against.

**Comment by stefanottili** [comment]
Open 1st file and then use “open in same layout” for the 2nd.

**Comment by ottumm** [comment]
Ah thanks that did it!

**Comment by ottumm** [comment]
For posterity, the menu option for me was File -> Open in Same Panel.
