### ISSUE TITLE
Fill Tool crashes KLayout

### ISSUE THREAD

**Issue by Sam-MSU** [KLayout/klayout#897]
Hello,

when using Fill (Tiling) tool, it crashes KLayout in my typical use case. It seems, the problem started in version 0.27 with the introduction of the tabbed Fill Tool window. Test files are attached. I use version 0.27.3 flatpak version from flathub on fedora.

When filling the "TOP" cell with the "Fill" cell I use:
Fill area -> All
Exclude area -> All visible layers
Fill Cell -> Fill cell -> Fill
Fill Cell -> Boundary layer -> 2/0

It works well if I change:
Exclude area -> Selected layers 
and select layer 1/0

It crashes when I use:
Exclude area -> Selected layers 
and select another empty layer defined from my layer properties.

All works as usual with v0.26.12

[fill_tool_crash_example.zip](https://github.com/KLayout/klayout/files/7073008/fill_tool_crash_example.zip)

**Comment by klayoutmatthias** [comment]
Awesome! Thanks for the well-prepared test case.

The problem occurs if a layer is selected as exclude which is empty - hence not a valid database layer. It's easy to fix and will go into the 0.27.4 version.

Thanks,

Matthias
