### ISSUE TITLE
The problem with number of points while creating circle with CIRCLE PCell

### ISSUE THREAD

**Issue by Kaomil** [KLayout/klayout#926]
Dear Sir/Madam,

I have recently faced the problem of creating the circle polygon with given distance between the points. In my case the distance is about 160nm. To create such circle polygon I used CIRCLE PCell with 5.5 micron radius and 210 points, converted PCell into static cell, and it worked well for me. However, when I tried to create circle with radius 18.84 micron and chose 780 points, the circle polygon appeared to be distorted after converting PCell to static cell: the number of points was 700 and the points wasn't evenly distributed along the circle. I noticed that the same problem happens, when I choose 300 points for 5.5 micron radius circle. So, beginning from some number of points, depending on the radius, the points of the circle become not evenly distributed. Is it a bug or something?

I managed this problem using ROUND.POLYGON PCell on the Box Polygon. It worked, I created the Circle polygon with radius 18.84 and with 780 evenly distributed points, BUT If I moved this polygon to another position (or copyed it and pasted it in the same layer) the number of points decreased to 700 and they become NOT evenly distributed. I believe KLayoyt shouldn't work like that. Could you help me please?

Sincerely,
Kamil Taziev.

**Comment by klayoutmatthias** [comment]
Does that solve the problem? I'd like to close this issue.
