### ISSUE TITLE
XML parser error: Expected '/' here: |    layer width function output

### ISSUE THREAD

**Issue by ahmednofal** [KLayout/klayout#927]
Hello Matthias, thank you for your work on this project. 

I am facing this error while trying to display a marker database xml file on top of a gds.gz file. The error is `XML parser error: Expected '/' here: |(75.85,40 .. in line 364, column 81` I traced it down to the offending line which is `<value>edge-pair: (75.86,46.8;75.85,46.8)|(75.85,46.81;75.86,46.81)</value>`. 
The pipe character is bugging klayout. This parsing error kills klayout and makes it exit. 
This xml report is a result of this drc rule.
`nwell.width(0.84, euclidian).output("nwell.1", "nwell.1 : min. nwell width : 0.84um")`, 
which is part of this DRC script: https://github.com/efabless/mpw_precheck/blob/2f2f4261ed2b59f8d21ac38fbffa7ccc6f7b9729/checks/tech-files/sky130A_mr.drc#L209
The offending GDS resides here: 
https://gitlab.com/um-ece/ftl-lab/hilas/designs/mpw2/-/blob/main/gds/user_analog_project_wrapper.gds.gz

To reproduce:
 `klayout -b -r sky130A_mr.drc -rd feol=true -rd input=<gds_path> -rd report=<xml_output_path>`

**Comment by klayoutmatthias** [comment]
No worries! :)

Your post made me aware that I should be more careful about not introducing enhancements which are not backward compatible.

Thanks,

Matthias
