### ISSUE TITLE
LVS: multi layer resistor connected through via

### ISSUE THREAD

**Issue by anadb** [KLayout/klayout#929]
Hi,

I would like to calculate resistance of structure depicted below. This is kind of chain of plates connected through via.
I didn't find out how to do in KLayout since there is only an example with one layer. I tried to make a connectin but it didn't help.

![image](https://user-images.githubusercontent.com/9407727/139914493-ce082b36-71f1-4b3b-9139-7366d6190c60.png)

The Xsection looks like this

![image](https://user-images.githubusercontent.com/9407727/140027262-56de51ed-1ae6-4bb5-9c45-8683e5cea7fe.png)

**Comment by klayoutmatthias** [comment]
This is a question, not a bug, right?

I'd like to advertise the forum (https://www.klayout.de/forum/) for support topics.

In your case, the question for me is what is the variable part of the resistor. If that is just the center upper metal part, then you will need some marker or label to identify that part. With this you can use the standard resistor model.

Matthias

**Comment by anadb** [comment]
Thank you for your answer, yes this is a question.

I registered on klayout forum but my mail was varified very recently. So I can transfer this question to the forum.
Anyway I need more details
