### ISSUE TITLE
Error reading DRC marker file

### ISSUE THREAD

**Issue by d-m-bailey** [KLayout/klayout#930]
klayout on mac0S won't read the DRC report for via spacing errors. 
version 0.26.10
macOS BigSur
Here's the error message `XML parser error: Expected '/' here: |(1810.12, .. in line 490, column 97`
```
   <category>'via4.2'</category>
   <cell>user_project_wrapper</cell>
   <visited>false</visited>
   <multiplicity>1</multiplicity>
   <image/>
   <values>
    <value>edge-pair: (1810.88,2176.28;1810.88,2177.08)|(1810.12,2177.08;1810.12,2176.28)</value>
   </values>
```
It complains about the `|` between the coordinates. When I change it to `/` like below, it works.
```
   <category>'via4.2'</category>
   <cell>user_project_wrapper</cell>
   <visited>false</visited>
   <multiplicity>1</multiplicity>
   <image/>
   <values>
    <value>edge-pair: (1810.88,2176.28;1810.88,2177.08)/(1810.12,2177.08;1810.12,2176.28)</value>
   </values>
```
[klayout_beol_check.xml.gz](https://github.com/KLayout/klayout/files/7489153/klayout_beol_check.xml.gz)

**Comment by klayoutmatthias** [comment]
Please see https://github.com/KLayout/klayout/issues/927. That's exactly the same issue. 

Please use a 0.27.x version of KLayout to open these files.

**Comment by d-m-bailey** [comment]
Sorry for the duplicate.

**Comment by klayoutmatthias** [comment]
No worries. You could not see it. It was closed already :)
