### ISSUE TITLE
 __file__ returns quoted path string In KLayout IDE

### ISSUE THREAD

**Issue by cheng1214** [KLayout/klayout#946]
Hi All,

In my case,  \__file__ returns "'C:/Users/Rui Cheng/KLayout/salt/siepic_tools/tech/GSiP/pymacros/GSiP Library.lym'",  which is seen as invalid path in many cases of Python.

I guess that the issue might be because of the name space of my usename folder? But that issue doesn't exist in my Spyder.

Currently, I have fixed the issue by using \__file__[1:-1].

I wondered if anyone could help fix this issue.

Thanking you!

**Comment by klayoutmatthias** [comment]
If fixed the issue which was related to the blank in the path.

However, if you are using the include feature (see https://www.klayout.de/doc-qt5/manual/drc_runsets.html#k_3), ```__file__``` (Python) or ```__FILE__``` (Ruby) will not report the true file name as the interpreters will see an include-expanded version.

Matthias
