### ISSUE TITLE
Deleting active cell leads to unrecoverable crash

### ISSUE THREAD

**Issue by dansharkey** [KLayout/klayout#951]
Steps to re-create:
1) Create new layout
2) Create cell e.g. "Top"
3) Create new layer e.g. 1/0
4) Create new subcell, e.g. "SubCell"
5) "Descend" into cell (ctrl-D on Windows)
6) Right-click and delete cell in the Cells dock.

Error message: `Internal error: ../../../src/tl/tl/tlReuseVector.h:277 mp_v->is_used (m_n) was not true`

Pressing ok leads to infinite loop with no way of escaping other than hard-quitting the app.

It's probably an unusual thing to do (delete the cell you are currently in), but it's happened to me a few times and sometimes lost me work.

Expected behaviour would be to either refuse to delete the cell, or delete the cell and change the active cell to one level higher of the hierarchy.

Many many thanks for such an amazing piece of software. Apologies if this bug has been reported already - I searched but did not find a report.

Version tested 0.27.5 on Windows 10 (64 bit).

**Comment by klayoutmatthias** [comment]
Thanks for this bug report. 

It's actually somewhat unusual to delete the cell you're sitting in :)

But of course there should be a better error than this and it should be recoverable.
