### ISSUE TITLE
2.5d view - Allow boolean layer operation

### ISSUE THREAD

**Issue by Grandement** [KLayout/klayout#952]
I would kindly ask for a new option for the 2.5d view. It would be very good to have an option in the config to allow boolean layer operation. E.g. to define metal slots by a specific layer.

Reference discussion:
https://www.klayout.de/forum/discussion/1993/2-5d-view-with-boolean-layer-operation#latest

**Comment by klayoutmatthias** [comment]
Hi have added a feature for this - in fact I have entirely reworked the whole view generation.

The price to pay is incompatibility: now the 2.5d view uses a script to generate the stack. This script is a superset of the DRC language which includes all the high- and low-end features of DRC, including booleans, sizing etc. In the simple form it is similar to - or at least easy to translate from - the basic form used so far.

**Comment by klayoutmatthias** [comment]
0.28 will have this new feature.
