### ISSUE TITLE
Pcell do not work for 0.27.6 on REDHAT7 CentOS7

### ISSUE THREAD

**Issue by YiLvErZhaoSanDianwei** [KLayout/klayout#969]
Dear @klayoutmatthias,

My Pcell code can work for version 0.27.5 on REDHAT7 CentOS7 linux system, however for version 0.27.6, I got following error:
maximumrecursion depth exceeded while calling a Python object in
PCellDeclaretion.wants_lazy_evaluation in
PCellDeclaration_Native.wants_lazy_evaluation in
PCellDeclaretion.wants_lazy_evaluation in
PCellDeclaration_Native.wants_lazy_evaluation in
PCellDeclaretion.wants_lazy_evaluation in
PCellDeclaration_Native.wants_lazy_evaluation in
PCellDeclaretion.wants_lazy_evaluation in
PCellDeclaration_Native.wants_lazy_evaluation in
PCellDeclaretion.wants_lazy_evaluation in
PCellDeclaration_Native.wants_lazy_evaluation in
PCellDeclaretion.wants_lazy_evaluation in
PCellDeclaration_Native.wants_lazy_evaluation in
PCellDeclaretion.wants_lazy_evaluation in
PCellDeclaration_Native.wants_lazy_evaluation in
PCellDeclaretion.wants_lazy_evaluation in
PCellDeclaration_Native.wants_lazy_evaluation in
PCellDeclaretion.wants_lazy_evaluation in

**Comment by lukasc-ubc** [comment]
I saw the same error in the Mac OSX build.

**Comment by RomainAlbert** [comment]
And I get the same error under windows.

**Comment by klayoutmatthias** [comment]
I'm sorry, something is broken here on 0.27.6.

Please use 0.27.5 until I have fixed this issue.

Apologies for this inconvenience.

Best regards,

Matthias

**Comment by Kazzz-S** [comment]
Dear @klayoutmatthias,

My PCells are all in **Ruby** and 0.26.7 (Windows, Linux, and Mac) crashed when it just started, opened a new design, or an existing PCell design.

I have (1) reimplemented `wants_lazy_evaluation()` method. Then, when I have (2) incidentally remade the `klayoutrc` file,
things went well on the three different platforms.
Now I get the following warnings on Mac:
```
Warning: QLayout: Attempting to add QLayout "" to QFrame "", which already has a layout
Warning: Populating font family aliases took 210 ms. Replace uses of missing font family "Sans Serif" with one that exists to avoid this cost. 
Warning: QLayout: Attempting to add QLayout "" to QFrame "", which already has a layout
```
Just for your information.

I'll rebuild DMGs if you release the next maintenance release 0.27.7 :-)

Thank you and best regards,
Kazzz-S

**Comment by klayoutmatthias** [comment]
I fixed the two QLayout Qt warnigns as well - thanks for reporting.

But you mean, you cannot load a GDS file with 0.26.7 which you have written with 0.27.6? Or is that a typo and you wanted to write "0.27.6"?

Thanks and best regards,

Matthias

**Comment by Kazzz-S** [comment]
> I fixed the two QLayout Qt warnigns as well - thanks for reporting.
> 
> But you mean, you cannot load a GDS file with 0.26.7 which you have written with 0.27.6? Or is that a typo and you wanted to write "0.27.6"?
> 
Sorry, just a silly typo ;-(

Kazzz-S

**Comment by klayoutmatthias** [comment]
Very good ... I understand better now :)

I'll publish the new release tomorrow with this fix.

Again, sorry for the inconvenience.

Best regards,

Matthias

**Comment by klayoutmatthias** [comment]
I'll close this issue as 0.27.7 should fix this problem now.

Thanks for reporting!

Matthias
