### ISSUE TITLE
detect which @toolbar combine mode is active

### ISSUE THREAD

**Issue by lukasc-ubc** [KLayout/klayout#974]
Dear @klayoutmatthias ,

I am wondering how I can detect which combine mode is active?  I am looking for a way to ask the @toolbar menus which item is active.

I've had many users accidentally change it to merge. When they draw a Path it comes out as a polygon, and the SiEPIC-Tools waveguide generator uses a Path as an input.  I'd like to add a check in the SiEPIC function that the combine mode is set to Add, and if not, issue a warning.

Here is what I tried:

> menu = pya.Application.instance().main_window().menu()

> menu.items('@toolbar.combine_mode')

['@toolbar.combine_mode.combine_mode_add', '@toolbar.combine_mode.combine_mode_merge', '@toolbar.combine_mode.combine_mode_erase', '@toolbar.combine_mode.combine_mode_mask', '@toolbar.combine_mode.combine_mode_diff']

> menu.is_menu('@toolbar.combine_mode')

False

> menu.action('@toolbar.combine_mode')

<pya.ActionBase object at 0x16502b840>

> menu.action('@toolbar.combine_mode.combine_mode_add')

<pya.ActionBase object at 0x16502b6c0>

> menu.action('@toolbar.combine_mode.combine_mode_add').is_enabled()

True

> menu.action('@toolbar.combine_mode.combine_mode_merge').is_enabled()

True

> menu.action('@toolbar.combine_mode.combine_mode_add').is_effective_visible()

True
> menu.action('@toolbar.combine_mode.combine_mode_merge').is_effective_visible()

True

> menu.action('@toolbar.combine_mode.combine_mode_merge').is_visible()

True

> menu.action('@toolbar.combine_mode.combine_mode_add').is_visible()

True

The actions allow you to change the combine mode:

> menu.action('@toolbar.combine_mode.combine_mode_merge').trigger()

<pya.ActionBase object at 0x16502b940>

> menu.action('@toolbar.combine_mode.combine_mode_add').trigger()

<pya.ActionBase object at 0x16502b6c0>

How do you detect which one is active?

On a related topic, when you select the "T" Technology icon, and choose a technology, it doesn't actually change it until you click on the "T".  It would be nice if the "T" behaved the same as the merge mode, namely when you choose the dropdown for the merge mode, it actually changes the mode.  Is there a reason you have "click to apply" in the tool tip?

thank you

**Comment by klayoutmatthias** [comment]
The active combination mode is a configuration property and can be obtained this way (Ruby):

```
RBA::MainWindow::instance().get_config("combine-mode")
```

This will give you "add", "merge" etc.

The "T" problem is an old one and something I can never get right. It's both the setting for new layouts and the current one plus there can potentially be multiple layouts ... this icon is not bidirectionally connected and I wasn't able so far to consistently implement such a thing. In fact, the "T" shouldn't be in the tool bar at all. From the data perspective, it's more consistent to have the technology a layout property (as available in the "File/Layout Properties" page).

Matthias
