### ISSUE TITLE
Negative extensions with pathtype 4 - correct layout, but properties are displayed falsely

### ISSUE THREAD

**Issue by patrickschulz** [KLayout/klayout#997]
Negative path extension for paths of type 4 are supported by GDSII and work nicely in klayout. However, when one checks the object properties, the value is not displayed correctly. I've attached a screenshot to show the issue. It is easy to reproduce, one can just put in a negative number (e.g. 0.2).
![klayout_path_extension_issue](https://user-images.githubusercontent.com/18125850/153600762-32300f71-1723-4be1-8027-fbc3c1387c00.png)
In the image you can see the path is correct in the layout, however its start extension is incorrect.

**Comment by klayoutmatthias** [comment]
Thanks for reporting. That's easy to fix.
